import test from 'node:test'
import assert from 'node:assert/strict'
import { randomUUID } from 'node:crypto'
import { applyFinanceCommand, emptyFinance, financeReport, percentCents } from '../shared/finance.mjs'

const actorId = randomUUID(), brokerId = randomUUID(), propertyId = randomUUID()
const context = { actorId, now: '2026-09-16T18:00:00Z', members: [{ id: brokerId, name: 'Corretor real', role: 'corretor', active: true }], properties: [{ id: propertyId, title: 'Imóvel real' }] }
const period = { from: '2026-09-01', to: '2026-09-30', asOf: '2026-09-16' }
const command = (state, type, data) => applyFinanceCommand(state, { type, data }, context)
const account = (state, amount = 0, data = {}) => command(state, 'account.save', { name: 'Conta principal', kind: 'bank', openingDate: '2026-01-01', openingBalanceCents: amount, ...data })
const entry = (state, data = {}) => command(state, 'entry.save', { description: 'Honorários de venda', category: 'sale_fee', amountCents: 10000, recognition: 'recognized', competenceDate: '2026-09-01', dueDate: '2026-09-10', behavior: 'variable', ...data })
const settle = (state, item = state.entries.at(-1), data = {}) => command(state, 'entry.settle', { id: item.id, accountId: state.accounts[0].id, settledDate: '2026-09-10', ...data })
const operation = (state, data = {}) => command(state, 'operation.create', { title: 'Venda de imóvel', kind: 'sale', amountCents: 100001, commissionBps: 3333, directCostCents: 5000, reserveBps: 1000, brokerId, propertyId, competenceDate: '2026-09-01', dueDate: '2026-09-10', ...data })

test('empty setup does not invent balances, partners, percentages or return estimates', () => {
  const state = emptyFinance()
  const report = financeReport(state, period)
  assert.equal(state.settings.reserveBps, null)
  assert.equal(report.cash.balanceCents, 0)
  assert.equal(report.cash.targetCents, null)
  assert.equal(report.payback.monthsEstimate, null)
  assert.equal(report.distribution.ready, false)
  assert.deepEqual(report.brokers, [])
})

test('currency uses exact integer cents and basis point rounding, including half cent', () => {
  assert.equal(percentCents(100001, 3333), 33330)
  assert.equal(percentCents(1, 5000), 1)
  assert.equal(percentCents(1_000_000_000_000, 9999), 999900000000)
  assert.throws(() => entry(emptyFinance(), { amountCents: 1.25 }), /inteiro/)
  assert.throws(() => entry(emptyFinance(), { amountCents: -1 }), /inteiro/)
  assert.throws(() => entry(emptyFinance(), { amountCents: Infinity }), /inteiro/)
})

test('DRE competence and bank cash settlement stay separate, including prepaid cash', () => {
  let state = account(emptyFinance())
  state = entry(state, { competenceDate: '2026-10-01', dueDate: '2026-09-10' })
  state = settle(state)
  assert.equal(financeReport(state, period).cash.balanceCents, 10000)
  assert.equal(financeReport(state, period).dre.combined.revenueCents, 0)
  assert.equal(financeReport(state, { ...period, from: '2026-10-01', to: '2026-10-31' }).dre.combined.revenueCents, 10000)
  assert.throws(() => settle(entry(state), undefined, { settledDate: '2026-09-17' }), /futuro/)
})

test('transfers balance individual accounts without revenue, expense, MRR or profit', () => {
  let state = account(emptyFinance(), 100000)
  state = account(state, 20000, { name: 'Conta de reserva' })
  state = entry(state, { category: 'transfer', amountCents: 30000 })
  state = settle(state, undefined, { destinationAccountId: state.accounts[1].id })
  const report = financeReport(state, period)
  assert.deepEqual(report.cash.accounts.map(item => item.balanceCents), [70000, 50000])
  assert.equal(report.cash.balanceCents, 120000)
  assert.equal(report.dre.combined.netProfitCents, 0)
  assert.equal(report.period.paidCents, 0)
  assert.equal(report.period.receivedCents, 0)
  assert.throws(() => settle(entry(state, { category: 'transfer' }), undefined, { destinationAccountId: state.accounts[0].id }), /diferente/)
})

test('owner rent cash remains held third-party funds; only management fees are company revenue', () => {
  let state = account(emptyFinance(), 20000, { openingThirdPartyCents: 5000 })
  state = settle(entry(state, { category: 'third_party_in', amountCents: 100000 }))
  state = settle(entry(state, { category: 'third_party_out', amountCents: 90000 }))
  state = settle(entry(state, { category: 'management_fee', amountCents: 10000 }))
  const report = financeReport(state, period)
  assert.equal(report.cash.balanceCents, 40000)
  assert.equal(report.cash.thirdPartyHeldCents, 15000)
  assert.equal(report.cash.availableCents, 25000)
  assert.equal(report.dre.combined.revenueCents, 10000)
  assert.equal(report.payback.recoveredCents, 10000)
})

test('recurring monthly fees generate once per month and projections do not double count', () => {
  let state = account(emptyFinance())
  state = command(state, 'recurrence.save', { name: 'Gestão mensal', category: 'management_fee', amountCents: 10000, startMonth: '2026-09', dueDay: 20, active: true })
  const recurrenceId = state.recurrences[0].id
  state = command(state, 'recurrence.generate', { id: recurrenceId, month: '2026-09' })
  state = command(state, 'recurrence.generate', { id: recurrenceId, month: '2026-09' })
  assert.equal(state.entries.length, 1)
  let report = financeReport(state, period)
  assert.equal(report.mrrCents, 10000)
  assert.equal(report.arrCents, 120000)
  assert.equal(report.projections[0].receivableCents, 10000)
  assert.equal(report.projections[1].receivableCents, 10000)
  assert.equal(report.dre.combined.revenueCents, 0)
  state = settle(state)
  report = financeReport(state, period)
  assert.equal(report.projections[0].receivableCents, 0)
  assert.equal(report.dre.combined.revenueCents, 10000)
  state = command(state, 'entry.cancel', { id: state.entries[0].id, reason: 'Competência cancelada' })
  state = command(state, 'recurrence.generate', { id: recurrenceId, month: '2026-09' })
  assert.equal(state.entries.length, 1)
})

test('unmaterialized recurring expenses project while one-off rents and thirds never inflate MRR', () => {
  let state = account(emptyFinance(), 10000)
  for (const [category, amountCents] of [['software', 25000], ['third_party_in', 100000], ['rental_fee', 10000]]) {
    state = command(state, 'recurrence.save', { name: `Recorrência ${category}`, category, amountCents, startMonth: '2026-09', endMonth: '2026-09', dueDay: 20 })
  }
  state = command(state, 'settings.save', { cashTargetCents: 50000 })
  const report = financeReport(state, period)
  assert.equal(report.mrrCents, 0)
  assert.equal(report.projections[0].closingCents, 95000)
  assert.equal(report.projections[0].availableCents, -5000)
  assert.equal(report.projections[0].belowTarget, true)
  assert.equal(report.projections[1].receivableCents, 0)
})

test('operation links real broker/property and books only the EME fee with exact contributions', () => {
  let state = operation(account(emptyFinance()))
  assert.equal(state.entries.length, 3)
  let report = financeReport(state, period, context.members)
  assert.equal(report.dre.combined.revenueCents, 100001)
  assert.equal(report.dre.combined.directCostCents, 38330)
  assert.equal(report.brokers[0].name, 'Corretor real')
  assert.equal(report.brokers[0].contributionCents, 61671)
  assert.equal(report.brokers[0].operations, 1)
  assert.equal(report.cash.reserveSuggestedCents, 0)
  state = settle(state, state.entries[0])
  report = financeReport(state, period)
  assert.equal(report.cash.reserveSuggestedCents, 10000)
  assert.equal(report.dre.combined.netProfitCents, 61671)
  assert.throws(() => operation(state, { brokerId: randomUUID() }), /cadastro ativo/)
  assert.throws(() => operation(state, { propertyId: randomUUID() }), /cadastro ativo/)
  assert.throws(() => command(state, 'entry.save', { id: state.entries[0].id, amountCents: 2 }), /baixados/)
})

test('operation cancellation is atomic and keeps original entries and reason, never partial edits', () => {
  let state = operation(account(emptyFinance()))
  assert.throws(() => command(state, 'entry.cancel', { id: state.entries[0].id, reason: 'Reversão' }), /operação/)
  state = command(state, 'operation.cancel', { id: state.operations[0].id, reason: 'Contrato desfeito' })
  assert.equal(state.entries.length, 3)
  assert.equal(state.operations[0].status, 'cancelled')
  assert.ok(state.entries.every(item => item.status === 'cancelled' && item.cancelReason === 'Contrato desfeito'))
  assert.equal(financeReport(state, period).dre.combined.netProfitCents, 0)
})

test('manual DRE is traceable and separate from automatic values and bank balance', () => {
  let state = settle(entry(account(emptyFinance())))
  state = command(state, 'adjustment.save', { label: 'Despesa apropriada', group: 'opex', amountCents: 2000, competenceDate: '2026-09-01', reason: 'Documento conferido' })
  let report = financeReport(state, period)
  assert.equal(report.dre.automatic.netProfitCents, 10000)
  assert.equal(report.dre.manual.operatingExpensesCents, 2000)
  assert.equal(report.dre.combined.netProfitCents, 8000)
  assert.equal(report.cash.balanceCents, 10000)
  assert.throws(() => command(state, 'adjustment.save', { id: state.adjustments[0].id, amountCents: 1000 }), /histórico/)
  state = command(state, 'adjustment.cancel', { id: state.adjustments[0].id, reason: 'Documento substituído' })
  report = financeReport(state, period)
  assert.equal(report.dre.combined.netProfitCents, 10000)
})

test('partner split requires full allocation, rounds to exact total and respects protected cash', () => {
  let state = settle(entry(account(emptyFinance()), { amountCents: 101 }))
  state = command(state, 'partner.save', { name: 'Sócio A', shareBps: 3333 })
  assert.equal(financeReport(state, period).distribution.ready, false)
  state = command(state, 'partner.save', { name: 'Sócio B', shareBps: 3333 })
  state = command(state, 'partner.save', { name: 'Sócio C', shareBps: 3334 })
  let report = financeReport(state, period)
  assert.equal(report.distribution.eligibleCents, 101)
  assert.equal(report.distribution.shares.reduce((total, item) => total + item.amountCents, 0), 101)
  assert.throws(() => command(state, 'partner.save', { name: 'Sócio extra', shareBps: 1 }), /100%/)
  state = command(state, 'settings.save', { cashTargetCents: 50 })
  report = financeReport(state, period)
  assert.equal(report.distribution.eligibleCents, 51)
  assert.equal(report.distribution.shares.reduce((total, item) => total + item.amountCents, 0), 51)
})

test('loss or low available cash never generates a positive profit withdrawal proposal', () => {
  let state = settle(entry(account(emptyFinance(), 100000), { category: 'marketing', amountCents: 10000 }))
  state = command(state, 'partner.save', { name: 'Sócio único', shareBps: 10000 })
  assert.equal(financeReport(state, period).distribution.eligibleCents, 0)
  state = entry(state, { category: 'sale_fee', amountCents: 200000 })
  state = command(state, 'settings.save', { cashTargetCents: 100000 })
  assert.equal(financeReport(state, period).dre.combined.netProfitCents, 190000)
  assert.equal(financeReport(state, period).distribution.eligibleCents, 0)
})

test('payback excludes capital and loans and uses only completed cash months for estimate', () => {
  let state = account(emptyFinance())
  state = command(state, 'settings.save', { initialInvestmentCents: 100000 })
  state = settle(entry(state, { category: 'capital_in', amountCents: 100000 }))
  state = settle(entry(state, { category: 'loan_in', amountCents: 200000 }))
  assert.equal(financeReport(state, period).payback.recoveredCents, 0)
  assert.equal(financeReport(state, period).payback.monthsEstimate, null)
  state = settle(entry(state, { amountCents: 10000 }), undefined, { settledDate: '2026-07-10' })
  state = settle(entry(state, { amountCents: 10000 }), undefined, { settledDate: '2026-08-10' })
  state = settle(entry(state, { amountCents: 5000 }))
  const report = financeReport(state, period)
  assert.equal(report.payback.recoveredCents, 25000)
  assert.equal(report.payback.remainingCents, 75000)
  assert.equal(report.payback.monthsEstimate, 8)
})

test('dates, bank opening balances, settlement history and cancellation reasons are validated', () => {
  assert.throws(() => entry(emptyFinance(), { competenceDate: '2026-02-30' }), /data válida/)
  let state = account(emptyFinance(), 100)
  assert.throws(() => command(state, 'account.save', { name: 'Conta', openingDate: '2026-01-01', openingBalanceCents: 100, openingThirdPartyCents: 101 }), /superar/)
  state = settle(entry(state))
  assert.throws(() => command(state, 'account.save', { id: state.accounts[0].id, openingBalanceCents: 2 }), /preservado/)
  assert.throws(() => command(state, 'entry.cancel', { id: state.entries[0].id, reason: '' }), /Motivo/)
  const before = structuredClone(state)
  const changed = command(state, 'entry.cancel', { id: state.entries[0].id, reason: 'Correção documentada' })
  assert.deepEqual(state, before)
  assert.equal(changed.entries[0].status, 'cancelled')
  assert.equal(changed.entries[0].amountCents, 10000)
  assert.equal(changed.entries[0].settledDate, '2026-09-10')
})

test('retained management fee reclassifies owner funds without inventing a second bank deposit', () => {
  let state = account(emptyFinance())
  state = settle(entry(state, { category: 'third_party_in', amountCents: 100000, propertyId }))
  state = settle(entry(state, { category: 'third_party_out', amountCents: 90000, propertyId }))
  state = settle(entry(state, { category: 'management_fee_retained', amountCents: 10000, propertyId }))
  const report = financeReport(state, period)
  assert.equal(report.cash.balanceCents, 10000)
  assert.equal(report.cash.thirdPartyHeldCents, 0)
  assert.equal(report.cash.availableCents, 10000)
  assert.equal(report.dre.combined.revenueCents, 10000)
  assert.equal(report.period.receivedCents, 100000)
  assert.equal(report.period.paidCents, 90000)
  assert.equal(report.period.operatingCashCents, 10000)
  assert.throws(() => settle(entry(state, { category: 'management_fee_retained', amountCents: 1, propertyId })), /saldo suficiente/)
  state = command(state, 'entry.cancel', { id: state.entries.at(-1).id, reason: 'Taxa corrigida' })
  assert.equal(financeReport(state, period).cash.balanceCents, 10000)
  assert.equal(financeReport(state, period).cash.thirdPartyHeldCents, 10000)
})

test('retention requires funds by the settlement date and property, and forecasts no new deposit', () => {
  let state = account(emptyFinance())
  state = settle(entry(state, { category: 'third_party_in', amountCents: 100000, propertyId }))
  let pending = entry(state, { category: 'management_fee_retained', amountCents: 10000, propertyId })
  assert.throws(() => settle(pending, undefined, { settledDate: '2026-09-09' }), /saldo suficiente/)
  const otherPropertyId = randomUUID()
  const expandedContext = { ...context, properties: [...context.properties, { id: otherPropertyId, title: 'Outro imóvel' }] }
  pending = applyFinanceCommand(state, { type: 'entry.save', data: { description: 'Taxa de outro imóvel', category: 'management_fee_retained', amountCents: 10000, propertyId: otherPropertyId, competenceDate: '2026-09-01', dueDate: '2026-09-10' } }, expandedContext)
  assert.throws(() => settle(pending), /vinculado a este imóvel/)
  state = command(state, 'recurrence.save', { name: 'Administração retida', category: 'management_fee_retained', amountCents: 10000, startMonth: '2026-09', dueDay: 20, propertyId })
  const report = financeReport(state, period)
  assert.equal(report.mrrCents, 10000)
  assert.equal(report.projections[0].receivableCents, 0)
  assert.equal(report.projections[0].retainedFeesCents, 10000)
  assert.equal(report.projections[0].closingCents, 100000)
  assert.equal(report.projections[0].availableCents, 10000)
})

test('past-month distribution still protects current bills and ignores future competence profit', () => {
  let state = settle(entry(account(emptyFinance()), { competenceDate: '2026-08-01', amountCents: 100000 }))
  state = command(state, 'partner.save', { name: 'Sócio', shareBps: 10000 })
  state = entry(state, { category: 'marketing', amountCents: 90000, competenceDate: '2026-09-01', dueDate: '2026-10-10' })
  const report = financeReport(state, { ...period, from: '2026-08-01', to: '2026-08-31' })
  assert.equal(report.distribution.payableHorizon, '2026-10-16')
  assert.equal(report.distribution.commitmentsCents, 90000)
  assert.equal(report.distribution.eligibleCents, 10000)
  state = entry(state, { amountCents: 100000, competenceDate: '2026-10-01' })
  assert.equal(financeReport(state, { ...period, from: '2026-10-01', to: '2026-10-31' }).distribution.eligibleCents, 0)
})

test('real settlement date uses the company timezone near UTC midnight', () => {
  const state = entry(account(emptyFinance()))
  assert.throws(() => applyFinanceCommand(state, { type: 'entry.settle', data: { id: state.entries[0].id, accountId: state.accounts[0].id, settledDate: '2026-09-17' } }, { ...context, now: '2026-09-17T01:30:00Z' }), /futuro/)
})

test('retention cannot consume property-tagged funds already paid by an untagged remittance', () => {
  let state = settle(entry(account(emptyFinance()), { category: 'third_party_in', amountCents: 10000, propertyId }))
  state = settle(entry(state, { category: 'third_party_out', amountCents: 10000 }))
  assert.throws(() => settle(entry(state, { category: 'management_fee_retained', amountCents: 10000, propertyId })), /saldo suficiente/)
})

test('profit proposal protects unmaterialized monthly costs without double-counting generated invoices', () => {
  let state = settle(entry(account(emptyFinance()), { amountCents: 100000 }))
  state = command(state, 'partner.save', { name: 'Sócio', shareBps: 10000 })
  state = command(state, 'recurrence.save', { name: 'Software mensal', category: 'software', amountCents: 30000, startMonth: '2026-09', dueDay: 10 })
  assert.equal(financeReport(state, period).distribution.commitmentsCents, 60000)
  assert.equal(financeReport(state, period).distribution.eligibleCents, 40000)
  state = command(state, 'recurrence.generate', { id: state.recurrences[0].id, month: '2026-09' })
  assert.equal(financeReport(state, period).distribution.commitmentsCents, 60000)
})
