import { test, expect } from '@playwright/test';
import { g400UnitsOnFloor } from '../src/developments/g400';
const route='/#/empreendimentos/g400';
test.beforeEach(async({page})=>{
  await page.route('**/api/public/properties',r=>r.fulfill({json:{properties:[]}}));
  await page.route('**/api/public/people',r=>r.fulfill({json:{people:[]}}));
});
test('G400 floor mapping follows original sheets, including the sixth floor exceptions',()=>{
  expect(g400UnitsOnFloor(1).map(item=>item.unit)).toEqual(['101','102','103','104','105']);
  expect(g400UnitsOnFloor(6).map(item=>item.unit)).toEqual(['601','602','603']);
  expect(g400UnitsOnFloor(7).map(item=>item.unit)).toEqual(['703','704','705']);
  expect(g400UnitsOnFloor(8)).toEqual([]);
});
test('floor selection, original galleries, readable plans, lighting and contact context',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(route);
  await expect(page).toHaveTitle(/G400.*Yclodema/);
  await expect(page.getByRole('heading',{level:1})).toContainText('G400');
  await page.locator('.development-image-world>img').evaluate((img:HTMLImageElement)=>img.decode());
  await page.screenshot({path:'test-results/g400-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'6º andar',exact:true}).click();
  await expect(page.getByTestId('g400-floor-band')).toHaveAttribute('data-floor','6');
  await expect(page.getByLabel('Unidades no projeto').getByRole('button')).toHaveCount(3);
  await expect(page.getByText('Disponibilidade a confirmar',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Ver planta da unidade 602',exact:true}).click();
  const dialog=page.getByRole('dialog');
  await expect(dialog.getByAltText('Tipo 2 · 209,30 m² privativos · 3 suítes')).toBeVisible();
  expect(decodeURIComponent(await dialog.getByRole('link',{name:'Conversar sobre o G400'}).getAttribute('href')||'')).toContain('unidade 602');
  await page.getByRole('button',{name:'Ampliar para ler os detalhes'}).click();
  await expect(dialog.locator('.g400-plan-enlarged')).toBeVisible();
  await page.getByRole('button',{name:'Ajustar planta à janela'}).click();
  await page.keyboard.press('ArrowRight');
  await expect(dialog.getByAltText('Tipo 3 · 215,90 m² privativos · 3 suítes')).toBeVisible();
  expect(decodeURIComponent(await dialog.getByRole('link',{name:'Conversar sobre o G400'}).getAttribute('href')||'')).not.toContain('unidade 602');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('button',{name:'Ver planta da unidade 602'})).toBeFocused();
  await page.getByRole('button',{name:'7º andar e coberturas',exact:true}).click();
  await page.getByRole('button',{name:'Ver planta da unidade 704'}).click();
  await expect(dialog.getByAltText('Triplex 1 · 444,56 m² privativos · 4 suítes')).toBeVisible();
  await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'Rooftop',exact:true}).click();
  await expect(dialog.getByAltText('Rooftop lounge')).toBeVisible();
  await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'Fachadas',exact:true}).click();
  await expect(dialog.getByAltText('Vista BR–Centro · Avenida Moreira Paz')).toBeVisible();
  for(let i=0;i<4;i++)await dialog.getByRole('button',{name:'Próxima imagem',exact:true}).click();
  await expect(dialog.getByAltText('Vista · Rua João Borges Pinto')).toBeVisible();
  await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'Noite',exact:true}).click();
  await expect(page.getByTestId('g400-stage')).toHaveClass(/--night/);
  await page.screenshot({path:'test-results/g400-night.png',fullPage:true});
  expect(errors).toEqual([]);
});
test('G400 mobile navigation, plan dialog and gallery have no horizontal overflow',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'});
  for(const width of [820,390,320]){
    await page.setViewportSize({width,height:844});
    await page.goto(route);
    await expect(page.getByRole('heading',{level:1})).toContainText('G400');
    await page.locator('.development-image-world>img').evaluate((img:HTMLImageElement)=>img.decode());
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await page.screenshot({path:`test-results/g400-mobile-${width}.png`,fullPage:true});
    await page.getByRole('button',{name:'Conhecer os interiores',exact:true}).click();
    await expect(page.getByRole('dialog').getByAltText('Salão de festas privativo · Triplex')).toBeVisible();
    await page.getByRole('button',{name:'Próxima imagem',exact:true}).click();
    await expect(page.getByRole('dialog').getByAltText('Suíte principal · Triplex 1')).toBeVisible();
    await page.keyboard.press('Escape');
    await page.getByRole('button',{name:'Recolher andares e plantas'}).click();
    await expect(page.getByLabel('Andares e plantas do G400')).toHaveCount(0);
    await page.getByRole('button',{name:'Explorar andares e plantas'}).click();
    await expect(page.getByLabel('Andares e plantas do G400')).toBeVisible();
  }
});
test('G400 3D camera, floor, lighting and graceful WebGL fallback',async({page})=>{
  test.setTimeout(90000);
  await page.goto(route);
  await page.getByRole('button',{name:'Explorar em 3D',exact:true}).click();
  const model=page.getByTestId('g400-model');
  await expect(model).toHaveAttribute('data-camera',/,/,{timeout:45000});
  const camera=await model.getAttribute('data-camera');
  await model.locator('canvas').focus();await page.keyboard.press('ArrowRight');
  await expect(model).not.toHaveAttribute('data-camera',camera!);
  await page.getByRole('button',{name:'4º andar',exact:true}).click();
  await expect(model).toHaveAttribute('data-floor','4');
  await page.getByRole('button',{name:'Noite',exact:true}).click();
  await expect(model).toHaveAttribute('data-lighting','night');
  await page.screenshot({path:'test-results/g400-model.png',fullPage:true});
  await model.locator('canvas').dispatchEvent('webglcontextlost');
  await page.getByRole('button',{name:'Voltar ao cenário'}).click();
  await expect(page.locator('.development-image-world')).toBeVisible();
});
test('G400 can be discovered from home and the official navigation',async({page})=>{
  await page.goto('/');
  await page.getByRole('button',{name:'Explorar',exact:true}).click();
  await page.getByRole('link',{name:'G400 · Yclodema',exact:true}).click();
  await expect(page).toHaveURL(/empreendimentos\/g400/);
  await page.getByRole('link',{name:'Voltar à coleção',exact:true}).click();
  await page.getByRole('link',{name:'Explorar G400',exact:true}).click();
  await expect(page.getByRole('heading',{level:1})).toContainText('G400');
});
