import {test,expect} from '@playwright/test';
const people=[{id:'first',name:'Primeira pessoa',role:'Fundador · CEO',bio:'Inovação e acompanhamento em cada etapa.\nUma segunda parte da apresentação.',photoUrl:'/assets/brand-marble-monogram.png',registration:'CRECI de teste'},{id:'second',name:'Segunda pessoa',role:'Consultora imobiliária',bio:'Apresentação própria da consultora.',photoUrl:'/assets/brand-marble-monogram.png',registration:''}];
test.beforeEach(async({page})=>{await page.route('**/api/public/properties',r=>r.fulfill({json:{properties:[]}}));await page.route('**/api/public/people',r=>r.fulfill({json:{people}}));});
test('portrait and name open dedicated profiles; keyboard, focus restoration and person navigation work',async({page})=>{
 await page.goto('/');const section=page.locator('#quem-faz-a-eme');await section.scrollIntoViewIfNeeded();const portrait=section.getByRole('button',{name:'Abrir perfil de Primeira pessoa'});await portrait.click();const modal=page.getByRole('dialog',{name:'Perfil de Primeira pessoa'});await expect(modal).toBeVisible();await expect(modal).toContainText('Uma segunda parte');await expect(modal).toContainText('CRECI de teste');await expect(page.locator('body')).toHaveCSS('overflow','hidden');
 const close=modal.getByRole('button',{name:'Fechar janela'});await close.focus();await page.keyboard.press('Shift+Tab');await expect(modal.getByRole('link',{name:'Iniciar uma conversa'})).toBeFocused();await page.keyboard.press('Tab');await expect(close).toBeFocused();await page.keyboard.press('Escape');await expect(modal).toHaveCount(0);await expect(portrait).toBeFocused();
 await section.getByRole('button',{name:'Primeira pessoa',exact:true}).click();await expect(modal).toBeVisible();await close.click();
 await section.getByRole('button',{name:'Próxima pessoa'}).click();await expect(section.getByRole('heading',{name:'Segunda pessoa'})).toBeVisible();await section.getByRole('button',{name:'Abrir perfil de Segunda pessoa'}).click();const second=page.getByRole('dialog',{name:'Perfil de Segunda pessoa'});await expect(second).toContainText('Apresentação própria da consultora.');await expect(second).not.toContainText('CRECI de teste');await second.getByRole('button',{name:'Fechar janela'}).click();
 await section.getByRole('button',{name:'Pessoa anterior'}).click();await expect(section.getByRole('heading',{name:'Primeira pessoa'})).toBeVisible();await section.getByRole('navigation').getByRole('button',{name:/Segunda pessoa/}).click();await expect(section.getByRole('heading',{name:'Segunda pessoa'})).toBeVisible();
});
test('small screens show the complete profile in a scrollable modal and respect reduced motion',async({page})=>{
 await page.setViewportSize({width:320,height:650});await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/');const section=page.locator('#quem-faz-a-eme');await section.scrollIntoViewIfNeeded();await expect(section.locator('.eme-person')).toHaveCSS('animation-name','none');await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await section.getByRole('button',{name:'Abrir perfil de Primeira pessoa'}).click();const modal=page.getByRole('dialog');await expect(modal).toBeVisible();await expect.poll(()=>modal.evaluate(e=>e.scrollWidth<=e.clientWidth)).toBe(true);await modal.getByRole('link',{name:'Iniciar uma conversa'}).scrollIntoViewIfNeeded();await expect(modal.getByRole('link',{name:'Iniciar uma conversa'})).toBeVisible();await page.keyboard.press('Escape');await expect(modal).toHaveCount(0);
});
