import { expect, test } from '@playwright/test';
import { approvalBlock, evaluations, initialState, isPortalState, scoreOf } from '../src/portal/model';

test('curadoria keeps documentation and completeness separate from the score', () => {
  expect(scoreOf([4,5,4,4])).toBe(85);
  expect(scoreOf([null,5,4,4])).toBeNull();
  const ready = { ...evaluations[1], reviewed: true };
  expect(approvalBlock(ready)).toBeNull();
  expect(approvalBlock({ ...ready, legal: 'Pendente' })).toContain('pendentes');
  expect(approvalBlock({ ...ready, scores: [2,5,5,5] })).toContain('régua');
  expect(approvalBlock({ ...ready, scores: [null,5,4,4] })).toContain('incompleta');
  expect(approvalBlock({ ...ready, stage: 'Entrada aprovada' })).not.toBeNull();
  expect(isPortalState(initialState())).toBe(true);
  expect(isPortalState({ ...initialState(), evaluations: [{ ...evaluations[0], scores: [99,3,3,3] }] })).toBe(false);
});
test('direct portal route, module navigation and browser history', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/portalselect/demo');
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Um olhar sobre toda a operação.');
  await expect(page.locator('.site-header')).toHaveCount(0);
  await page.getByRole('navigation', { name: 'Navegação do portal' }).getByRole('link', { name: 'Locações' }).click();
  await expect(page).toHaveURL(/\/portalselect\/demo\/locacoes$/);
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Contratos em acompanhamento' })).toBeVisible();
  await page.goBack();
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Um olhar sobre toda a operação.');
  await page.getByLabel('Buscar no portal', { exact: true }).fill('Mont');
  await page.locator('.ps-search-results').getByRole('button', { name: /Apartamento/ }).click();
  await expect(page.getByRole('dialog')).toContainText('AV-002');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  expect(errors).toEqual([]);
});
test('new incomplete evaluation persists and cannot bypass approval gates', async ({ page }) => {
  await page.goto('/portalselect/demo/avaliacoes');
  await page.getByRole('button', { name: 'Nova avaliação', exact: true }).click();
  await page.getByLabel('Nome do imóvel').fill('Casa teste do portal');
  await page.getByLabel('Cidade e região').fill('Caxias do Sul · RS');
  await page.getByRole('button', { name: 'Criar avaliação de exemplo' }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog).toContainText('Evidências incompletas');
  await dialog.getByRole('checkbox').check();
  await expect(dialog.getByRole('button', { name: 'Aprovar entrada de exemplo' })).toBeDisabled();
  await page.keyboard.press('Escape');
  await page.reload();
  await page.getByLabel('Buscar avaliações').fill('Casa teste do portal');
  await expect(page.locator('tbody tr')).toHaveCount(1);
  await expect(page.locator('tbody')).toContainText('Recebido');
});
test('human review is required and approved entry is saved without altering public catalog', async ({ page }) => {
  await page.goto('/portalselect/demo/avaliacoes');
  await page.getByRole('button', { name: 'Abrir dossiê de Apartamento Mont’Serrat' }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog.getByRole('button', { name: 'Aprovar entrada de exemplo' })).toBeDisabled();
  await dialog.getByRole('checkbox').check();
  await dialog.getByRole('button', { name: 'Aprovar entrada de exemplo' }).click();
  await expect(dialog).toContainText('Entrada aprovada neste exemplo');
  await expect(dialog.locator('.ps-history')).toContainText('sem publicação');
  await page.keyboard.press('Escape');
  await page.reload();
  await page.getByLabel('Buscar avaliações').fill('Mont');
  await expect(page.locator('tbody')).toContainText('Entrada aprovada');
});
test('requested changes record a reason and block approval', async ({ page }) => {
  await page.goto('/portalselect/demo/avaliacoes');
  await page.getByRole('button', { name: 'Abrir dossiê de Sala junto à praça' }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Solicitar ajuste no exemplo').fill('Confirmar a acessibilidade do acesso principal');
  await dialog.getByRole('button', { name: 'Registrar ajuste' }).click();
  await expect(dialog).toContainText('Ajustes solicitados');
  await expect(dialog.locator('.ps-pending-list')).toContainText('Confirmar a acessibilidade');
  await dialog.getByRole('checkbox').check();
  await expect(dialog.getByRole('button', { name: 'Aprovar entrada de exemplo' })).toBeDisabled();
});
test('conversation drafts are isolated and persist without sending messages', async ({ page }) => {
  await page.goto('/portalselect/demo/relacionamento');
  await page.getByLabel('Rascunho de resposta').fill('Rascunho para Ana — teste local');
  await page.getByLabel('Nota interna').fill('Conferir os horários disponíveis');
  await page.getByRole('button', { name: 'Guardar rascunho' }).click();
  await page.getByRole('button', { name: /Pedro Almeida/ }).click();
  await expect(page.getByLabel('Rascunho de resposta')).toHaveValue('');
  await page.getByRole('button', { name: /Ana Oliveira/ }).click();
  await expect(page.getByLabel('Rascunho de resposta')).toHaveValue('Rascunho para Ana — teste local');
  await page.reload();
  await expect(page.getByLabel('Nota interna')).toHaveValue('Conferir os horários disponíveis');
  await expect(page.getByRole('button', { name: /^Enviar/ })).toHaveCount(0);
});
test('rental statement separates owner money and administration revenue', async ({ page }) => {
  await page.goto('/portalselect/demo/locacoes');
  await page.locator('.ps-rental-list').getByRole('button', { name: /Apartamento do parque/ }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog).toContainText('R$ 4.200,00');
  await expect(dialog).toContainText('R$ 336,00');
  await expect(dialog).toContainText('R$ 3.864,00');
  await page.keyboard.press('Escape');
  await page.locator('.ps-rental-list').getByRole('button', { name: /Casa do bosque/ }).click();
  await expect(dialog).toContainText('R$ 3.800,00');
  await expect(dialog).toContainText('Não calculado');
});
test('mobile navigation, contained layout and public return', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/portalselect/demo');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Abrir navegação' }).click();
  await page.getByRole('navigation', { name: 'Navegação do portal' }).getByRole('link', { name: 'Central de IA' }).click();
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Inteligência em cada etapa.');
  await page.getByRole('button', { name: /Entrada e pré-avaliação/ }).click();
  await expect(page.getByRole('dialog')).toContainText('Integração em preparação');
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Abrir navegação' }).click();
  await page.getByRole('link', { name: 'Ir para o site' }).click();
  await expect(page.locator('.site-header')).toBeVisible();
  await expect(page.locator('.select-portal')).toHaveCount(0);
});
test('malformed saved data has an explicit recovery state', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('eme-select-portal-demo-v1', '{"version":1,"evaluations":[{}]}'));
  await page.goto('/portalselect/demo');
  await expect(page.getByRole('alert')).toContainText('não puderam ser lidos');
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible();
});
