import {confirmAction} from '../notices';
import {useEffect,useState} from 'react';
import {api} from './api';
import {preparePhoto} from './preparePhoto';
import {unitStatuses,type DevelopmentRecord,type DevelopmentConfig,type DevelopmentPlan,type ManagedUnit} from '../../shared/development.mjs';
import './listings.css';
const endpoint='/developments/moradas-da-serra';
export default function DevelopmentsWorkspace(){
 const [record,setRecord]=useState<DevelopmentRecord|null>(null),[config,setConfig]=useState<DevelopmentConfig|null>(null),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[confirmed,setConfirmed]=useState(false);
 const accept=(r:DevelopmentRecord)=>{setRecord(r);setConfig(r.config);setDirty(false);setConfirmed(false);};
 const load=()=>api<DevelopmentRecord>(endpoint).then(accept).catch(e=>setError(e.message));
 useEffect(()=>{void load();},[]);
 useEffect(()=>{const handler=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty]);
 function update(next:DevelopmentConfig){setConfig(next);setDirty(true);setConfirmed(false);setMessage('');}
 async function save(){if(!record||!config)return;const saved=await api<DevelopmentRecord>(endpoint,'PATCH',{version:record.version,config});accept(saved);return saved;}
 async function action(kind:'save'|'publish'|'unpublish'){setBusy(true);setError('');setMessage('');try{if(kind==='save'){await save();setMessage('Rascunho salvo. Publique a revisão para atualizar o site.');}else{const saved=await api<DevelopmentRecord>(endpoint+'/'+kind,'POST',{version:record!.version,...(kind==='publish'?{confirmed}:{})});accept(saved);setMessage(kind==='publish'?'Informações publicadas no cenário.':'Informações comerciais retiradas. O cenário permanece sem estoque confirmado.');}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function upload(id:string,file?:File){if(!file||!record||!config)return;setBusy(true);setError('');try{if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Use JPEG, PNG ou WebP.');const content=await preparePhoto(file);const saved=dirty?await save():record;const received=await api<DevelopmentRecord&{imageUrl:string}>(endpoint+'/images','POST',{version:saved!.version,content});setRecord(received);setConfig({...received.config,plans:received.config.plans.map(p=>p.id===id?{...p,imageUrl:received.imageUrl}:p)});setDirty(true);setConfirmed(false);setMessage('Planta recebida. Salve para vincular a imagem ao rascunho.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const planField=(id:string,patch:Partial<DevelopmentPlan>)=>update({...config!,plans:config!.plans.map(p=>p.id===id?{...p,...patch}:p)});
 const unitField=(id:string,patch:Partial<ManagedUnit>)=>update({...config!,units:config!.units.map(u=>u.id===id?{...u,...patch}:u)});
 const numeric=(v:string)=>v===''?null:Number(v);
 if(!config||!record)return <div className="ps-card">{error?<><p role="alert">{error}</p><button onClick={()=>void load()}>Tentar novamente</button></>:<p role="status">Carregando empreendimento…</p>}</div>;
 return <div className="pl-workspace development-editor">
  <div className="pl-intro"><div><h2>{config.name}</h2><p>Dados, plantas e estoque do cenário DeVille.</p></div><a className="ps-button" href="/#/empreendimentos/moradas-da-serra" target="_blank" rel="noreferrer">Abrir cenário público ↗</a></div>
  {error&&<div className="pt-error" role="alert">{error}<button className="ps-text-button" onClick={async()=>{if(!dirty||await confirmAction('Descartar alterações e recarregar a última versão?'))void load();}}>Recarregar versão salva</button></div>}
  {message&&<p className="pc-success" role="status">{message}</p>}
  <form className="ps-form" onSubmit={e=>{e.preventDefault();void action('save');}}><fieldset className="pc-fieldset" disabled={busy}>
   <section className="ps-card"><h3>Apresentação</h3><div className="pl-fields">{(['name','developer','location'] as const).map((key,i)=><label key={key}>{['Nome do empreendimento','Incorporadora','Localização'][i]}<input required maxLength={100} value={config[key]} onChange={e=>update({...config,[key]:e.target.value})}/></label>)}</div><label>Descrição<textarea maxLength={800} value={config.description} onChange={e=>update({...config,description:e.target.value})}/></label><label>Observações públicas<textarea maxLength={800} value={config.notes} onChange={e=>update({...config,notes:e.target.value})}/></label><div className="pl-fields">{config.towers.map(t=><label key={t.id}>Nome da torre {t.id.toUpperCase()}<input required maxLength={50} value={t.label} onChange={e=>update({...config,towers:config.towers.map(x=>x.id===t.id?{...x,label:e.target.value}:x)})}/></label>)}</div><p className="pc-help">O cenário atual representa duas torres com nove andares. Cadastre somente unidades e medidas confirmadas pela incorporadora.</p></section>
   <section className="ps-card"><h3>Plantas e metragens</h3><p>Cadastre cada tipologia uma vez e associe às unidades. A imagem será exibida no andar correspondente.</p>
    {!config.plans.length&&<p>Nenhuma planta cadastrada. As imagens comerciais da galeria continuam disponíveis como referência.</p>}
    {config.plans.map(p=><div className="development-editor-card" key={p.id}><div className="pl-fields"><label>Nome da planta<input required value={p.title} onChange={e=>planField(p.id,{title:e.target.value})}/></label>{(['area','bedrooms','suites','parking'] as const).map((key,i)=><label key={key}>{['Área privativa (m²)','Dormitórios','Suítes','Vagas'][i]}<input type="number" min="0" step={key==='area'?'.01':'1'} value={p[key]??''} onChange={e=>planField(p.id,{[key]:numeric(e.target.value)})}/></label>)}</div>{p.imageUrl&&<a href={p.imageUrl} target="_blank" rel="noreferrer"><img className="development-editor-plan" src={p.imageUrl} alt={p.title}/></a>}<label>Imagem da planta · JPEG, PNG ou WebP<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{void upload(p.id,e.target.files?.[0]);e.target.value='';}}/></label><button type="button" className="ps-text-button" disabled={config.units.some(u=>u.planId===p.id)} onClick={()=>update({...config,plans:config.plans.filter(x=>x.id!==p.id)})}>Remover planta</button>{config.units.some(u=>u.planId===p.id)&&<small>Desvincule as unidades para remover esta planta.</small>}</div>)}
    <button type="button" className="ps-button" disabled={config.plans.length>=30} onClick={()=>update({...config,plans:[...config.plans,{id:crypto.randomUUID(),title:'Nova planta',area:null,bedrooms:null,suites:null,parking:null,imageUrl:''}]})}>Adicionar planta</button>
   </section>
   <section className="ps-card"><h3>Unidades por torre e andar</h3><p>Disponíveis podem receber consultas; reservadas e vendidas aparecem como indisponíveis. Andares sem cadastro ficam “a confirmar”.</p>
    {config.units.map(u=><div className="development-editor-card" key={u.id}><div className="pl-fields"><label>Identificação da unidade<input required value={u.label} onChange={e=>unitField(u.id,{label:e.target.value})}/></label><label>Torre<select value={u.tower} onChange={e=>unitField(u.id,{tower:e.target.value as ManagedUnit['tower']})}>{config.towers.map(t=><option key={t.id} value={t.id}>{t.label}</option>)}</select></label><label>Andar<input type="number" required min="1" max="9" value={u.floor} onChange={e=>unitField(u.id,{floor:Number(e.target.value)})}/></label><label>Planta<select value={u.planId} onChange={e=>unitField(u.id,{planId:e.target.value})}><option value="">A confirmar</option>{config.plans.map(p=><option key={p.id} value={p.id}>{p.title}{p.area?` · ${p.area} m²`:''}</option>)}</select></label><label>Situação<select value={u.status} onChange={e=>unitField(u.id,{status:e.target.value as ManagedUnit['status']})}>{Object.entries(unitStatuses).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Preço de venda (R$)<input type="number" min="0" step=".01" value={u.price??''} onChange={e=>unitField(u.id,{price:numeric(e.target.value)})}/></label><label>Posição / orientação solar<input value={u.orientation} onChange={e=>unitField(u.id,{orientation:e.target.value})}/></label></div><button type="button" className="ps-text-button" onClick={async()=>{if(await confirmAction(`Remover a unidade ${u.label||'sem identificação'} do rascunho?`))update({...config,units:config.units.filter(x=>x.id!==u.id)});}}>Remover unidade</button></div>)}
    <button type="button" className="ps-button" disabled={config.units.length>=300} onClick={()=>update({...config,units:[...config.units,{id:crypto.randomUUID(),tower:'a',floor:1,label:'',planId:'',status:'unknown',price:null,orientation:''}]})}>Adicionar unidade</button>
   </section>
   <section className="ps-card"><h3>Salvar e publicar</h3><p>{dirty?'Há alterações não salvas.':record.publishedAt?`Última publicação: ${new Date(record.publishedAt).toLocaleString('pt-BR')}.`:'Nenhum estoque comercial publicado.'}</p><button className="ps-button ps-button--primary" type="submit">{busy?'Salvando…':'Salvar rascunho'}</button><label className="development-editor-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} disabled={dirty}/>Conferi as plantas, as medidas, a disponibilidade e a autorização de divulgação.</label><button type="button" className="ps-button ps-button--primary" disabled={dirty||!confirmed} onClick={()=>void action('publish')}>Publicar revisão no site</button>{record.published&&<button type="button" className="ps-text-button" onClick={async()=>{if(await confirmAction('Retirar as informações comerciais publicadas do empreendimento?'))void action('unpublish');}}>Retirar informações comerciais do site</button>}</section>
  </fieldset></form>
 </div>;
}
