import {preparePhoto} from './preparePhoto';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {ArrowLeft,ArrowRight,ArrowUp,ArrowDown,Plus,ExternalLink,Trash2,Check,House} from 'lucide-react';
import {api,ApiError,type TeamUser,type CaseDetails} from './api';
import {emptyDraft,listingTypes,type Draft,type Listing,type Photo} from './listingModel';
import './listings.css';
export default function ListingsWorkspace({user}:{user:TeamUser}){
 const [items,setItems]=useState<Listing[]>([]),[item,setItem]=useState<Listing|null>(null),[editing,setEditing]=useState(false),[draft,setDraft]=useState<Draft>({...emptyDraft}),[photos,setPhotos]=useState<Photo[]>([]),[evaluationId,setEvaluationId]=useState<string>();
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[dirty,setDirty]=useState(false),[confirm,setConfirm]=useState(false),[uploadProgress,setUploadProgress]=useState('');const fileInput=useRef<HTMLInputElement>(null);
 const load=()=>api<{listings:Listing[]}>('/listings').then(r=>setItems(r.listings));
 useEffect(()=>{let active=true;load().catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});const id=new URLSearchParams(location.search).get('avaliacao');if(id){(async()=>{try{const existing=await api<Listing>('/listings/'+id);if(active){accept(existing);setEditing(true);}}catch(e){if(!(e instanceof ApiError)||e.status!==404)throw e;const r=await api<CaseDetails>('/evaluations/'+id);if(active){setEvaluationId(id);setDraft({...emptyDraft,title:r.evaluation.title,city:r.evaluation.city,type:r.evaluation.type,ownerName:r.evaluation.owner,operation:r.evaluation.operation==='Locação'?'alugar':'comprar'});setEditing(true);setDirty(true);}}})().catch(e=>{if(active)setError(e.message);});}return()=>{active=false;};},[]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>e.preventDefault();window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 function accept(value:Listing){setItem(value);setDraft(value.draft);setPhotos(value.photos);setDirty(false);setConfirm(false);setItems(old=>[value,...old.filter(x=>x.id!==value.id)]);}
 function edit(value:Listing|null){setError('');setMessage('');setEvaluationId(undefined);setConfirm(false);setItem(value);setDraft(value?.draft||{...emptyDraft});setPhotos(value?.photos||[]);setEditing(true);setDirty(!value);}
 function field<K extends keyof Draft>(key:K,value:Draft[K]){setDraft(prev=>({...prev,[key]:value}));setDirty(true);setConfirm(false);}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await api<Listing>(item?'/listings/'+item.id:'/listings',item?'PATCH':'POST',item?{version:item.version,draft,photos:photos.map(({id,caption})=>({id,caption}))}:{draft,...(evaluationId?{evaluationId}:{})});accept(result);setMessage('Cadastro salvo. Continue pelas fotografias e pela curadoria.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function upload(files:File[]){if(!item)return;setError('');setMessage('');setBusy(true);let current=item;try{if(files.length+photos.length>20)throw Error('Cada imóvel pode ter até 20 fotografias.');for(let i=0;i<files.length;i++){const file=files[i];if(file.size>8*1024*1024)throw Error(file.name+': limite de 8 MB por foto.');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error(file.name+': use JPEG, PNG ou WebP.');setUploadProgress(`Preparando foto ${i+1} de ${files.length}…`);const content=await preparePhoto(file);current=await api<Listing>('/listings/'+current.id+'/photos','POST',{version:current.version,content,caption:''});accept(current);}setMessage('Fotografias salvas. Descreva cada ambiente e escolha a ordem da galeria.');}catch(e){setError((e as Error).message+' As fotos já concluídas foram preservadas.');}finally{setBusy(false);setUploadProgress('');if(fileInput.current)fileInput.current.value='';}}
 function move(index:number,step:number){const next=[...photos];[next[index],next[index+step]]=[next[index+step],next[index]];setPhotos(next);setDirty(true);setConfirm(false);}
 async function publish(action:'publish'|'unpublish'){if(!item)return;setBusy(true);setError('');try{const value=await api<Listing>('/listings/'+item.id+'/'+action,'POST',{version:item.version,confirmed:confirm});accept(value);setMessage(action==='publish'?'Anúncio publicado na coleção EME.':'Anúncio retirado do catálogo.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const textField=(label:string,key:keyof Draft,required=false)=><label>{label}<input required={required} maxLength={1200} value={String(draft[key]??'')} onChange={e=>field(key,e.target.value as never)}/></label>;
 const numField=(label:string,key:keyof Draft,step='0.01')=><label>{label}<input type="number" min="0" step={step} value={draft[key]??''} onChange={e=>field(key,(e.target.value===''?null:Number(e.target.value)) as never)}/></label>;
 return <div className="pl-workspace">{error&&<div className="pt-error" role="alert">{error}</div>}{message&&<p className="pc-success" role="status">{message}</p>}
 {!editing?<><div className="pl-intro"><div><h2>Imóveis da EME</h2><p>Do primeiro cadastro à apresentação de cada detalhe.</p></div><button className="ps-button ps-button--primary" onClick={()=>edit(null)}><Plus size={17}/>Cadastrar imóvel</button></div>{loading?<p role="status">Carregando imóveis…</p>:items.length?<div className="pl-list">{items.map(v=><button className="pl-list-item" key={v.id} onClick={()=>edit(v)}>{v.photos[0]?<img src={v.photos[0].url} alt=""/>:<span className="pl-no-photo"><House size={25}/></span>}<span><strong>{v.draft.title}</strong><small>{v.draft.city} · {v.draft.type}</small><em>{v.published?'Publicado':v.stage} · {v.photos.length} fotos</em></span><ArrowRight size={18}/></button>)}</div>:<div className="ps-card ps-empty"><House size={32}/><h3>Um lugar real. Uma apresentação à altura.</h3><p>Cadastre as informações e as fotos do primeiro imóvel. A divulgação acontece depois da curadoria.</p><button className="ps-button" onClick={()=>edit(null)}>Cadastrar primeiro imóvel</button></div>}</>:<>
 <div className="pl-editor-top"><button className="ps-text-button" disabled={busy} onClick={()=>{if(dirty&&!window.confirm('Sair sem salvar as alterações deste cadastro?'))return;setEditing(false);setDirty(false);load().catch(e=>setError(e.message));}}><ArrowLeft size={17}/>Todos os imóveis</button><span className="ps-tag">{item?(item.published?'Publicado':item.stage):'Novo cadastro'}</span>{item&&<a className="ps-button" href={'/portalselect/previa/'+item.id} target="_blank" rel="noopener noreferrer">Ver prévia salva<ExternalLink size={15}/></a>}</div>
 <form className="ps-form pl-editor" onSubmit={save}><fieldset disabled={busy} className="pc-fieldset"><section className="ps-card"><span className="ps-overline">01 / IDENTIDADE DO IMÓVEL</span><h2>O essencial, com precisão.</h2><div className="pl-fields">{textField('Título do anúncio','title',true)}{textField('Cidade e estado','city',true)}{textField('Bairro ou região pública','neighborhood')}<label>Tipo<select value={draft.type} onChange={e=>{field('type',e.target.value);if(e.target.value==='Casa em condomínio')field('condominium','horizontal');}}>{listingTypes.map(t=><option key={t}>{t}</option>)}</select></label><label>Ambiente<select value={draft.environment} onChange={e=>field('environment',e.target.value as Draft['environment'])}>{[['urbano','Urbano'],['litoral','Litoral'],['serra','Serra'],['comercial','Comercial'],['terrenos','Terrenos'],['industrial','Industrial']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Condomínio<select value={draft.condominium} onChange={e=>field('condominium',e.target.value as Draft['condominium'])}><option value="">Não informado / não se aplica</option><option value="horizontal">Horizontal</option><option value="vertical">Vertical</option></select></label></div><p className="pc-help">O anúncio mostra somente a região informada aqui. Não inclua nome do proprietário, telefone particular ou número da unidade.</p></section>
 <section className="ps-card"><span className="ps-overline">DADOS INTERNOS · SOMENTE A EQUIPE</span><h2>Informações reservadas.</h2>{textField('Endereço completo · privado','privateAddress')}<div className="pl-fields">{textField('Nome do proprietário · privado','ownerName')}{textField('Contato do proprietário · privado','ownerContact')}</div><p className="pc-help">Estes campos não fazem parte do anúncio nem da resposta pública do catálogo.</p></section><section className="ps-card"><span className="ps-overline">02 / CONDIÇÕES E CARACTERÍSTICAS</span><h2>Informação para uma boa escolha.</h2><div className="pl-fields"><label>Finalidade<select value={draft.operation} onChange={e=>field('operation',e.target.value as Draft['operation'])}><option value="comprar">Venda</option><option value="alugar">Locação</option></select></label>{numField(draft.operation==='alugar'?'Aluguel mensal (R$)':'Preço de venda (R$)','price')}{numField('Área informada (m²)','area')}{numField('Quartos','bedrooms','1')}{numField('Suítes','suites','1')}{numField('Vagas','parking','1')}{numField('Condomínio mensal (R$)','condominiumFee')}{numField('IPTU anual (R$)','propertyTax')}</div>{textField('Observações sobre despesas e área','costNotes')}<p className="pc-help">Deixe vazio o que não foi informado; zero significa ausência confirmada da despesa ou característica.</p></section>
 <section className="ps-card"><span className="ps-overline">03 / APRESENTAÇÃO E CURADORIA</span><h2>Conte o que torna este lugar especial.</h2><label>Descrição do imóvel<textarea rows={6} maxLength={5000} value={draft.description} onChange={e=>field('description',e.target.value)} placeholder="Descreva os espaços, a luz, os materiais, o entorno e as condições verificadas. Evite promessas que não podem ser comprovadas."/></label><div className="pl-fields"><label>Características · uma por linha<textarea rows={4} maxLength={1200} value={draft.features} onChange={e=>field('features',e.target.value)} placeholder={'Jardim privativo\nSala integrada à varanda'}/></label><label>Diferenciais EME · um por linha<textarea rows={4} maxLength={1200} value={draft.reasons} onChange={e=>field('reasons',e.target.value)} placeholder={'Integração entre espaços internos e jardim\nPlanta funcional e bem iluminada'}/></label></div></section>
 <section className="ps-card"><span className="ps-overline">04 / FOTOGRAFIAS REAIS</span><h2>A experiência começa pelo olhar.</h2><p className="pc-help">A primeira foto será a capa. Use até 20 fotos JPEG, PNG ou WebP, até 8 MB cada. As fotos são preparadas antes do envio. A galeria mantém a fotografia atual até a próxima estar pronta e faz uma transição gradual.</p><input ref={fileInput} className="pl-file" type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={!item||dirty||busy} aria-label="Adicionar fotografias do imóvel" onChange={e=>upload(Array.from(e.target.files||[]))}/>{!item||dirty?<p className="pc-help">Salve o cadastro antes de adicionar fotos.</p>:<p className="pc-help">Prefira imagens nítidas e autorizadas, sem pessoas ou informações privadas.</p>}{uploadProgress&&<p role="status">{uploadProgress}</p>}<div className="pl-photo-grid">{photos.map((p,i)=><article className="pl-photo" key={p.id}><div><img src={p.url} alt={p.caption||'Foto aguardando descrição'}/><span>{i===0?'Capa':String(i+1).padStart(2,'0')}</span></div><label>Ambiente da foto {i+1}<input value={p.caption} maxLength={180} placeholder="Ex.: sala de estar vista para o jardim" onChange={e=>{setPhotos(photos.map(x=>x.id===p.id?{...x,caption:e.target.value}:x));setDirty(true);}}/></label><div className="pl-photo-tools"><button type="button" className="ps-icon" disabled={!i} aria-label={'Mover foto '+(i+1)+' para antes'} onClick={()=>move(i,-1)}><ArrowUp size={16}/></button><button type="button" className="ps-icon" disabled={i===photos.length-1} aria-label={'Mover foto '+(i+1)+' para depois'} onClick={()=>move(i,1)}><ArrowDown size={16}/></button><button type="button" className="ps-text-button" onClick={()=>{setPhotos(photos.filter(x=>x.id!==p.id));setDirty(true);}}><Trash2 size={14}/>Remover</button></div></article>)}</div></section>
 </fieldset><div className="pl-save"><button className="ps-button ps-button--primary" disabled={busy||!dirty}><Check size={17}/>{busy?'Salvando…':'Salvar cadastro'}</button><small>{dirty?'Alterações não salvas':'Versão salva no servidor'}</small></div></form>
 {item&&<section className="ps-card pl-publish"><span className="ps-overline">05 / REVISÃO E PUBLICAÇÃO</span><h2>Pronto para apresentar?</h2>{item.blockers.length>0&&<ul>{item.blockers.map(v=><li key={v}>{v}</li>)}</ul>}<a className="ps-button" href={'/portalselect/avaliacoes?imovel='+item.id}>Abrir curadoria<ArrowRight size={16}/></a><p className="pc-help">Alterar dados ou fotos retira uma publicação anterior e exige nova conferência da curadoria. A prévia usa a versão salva. Após a publicação, o anúncio fica disponível na coleção conectada a este portal.</p>{user.role==='admin'&&<>{!item.published&&<label className="pl-confirm"><input type="checkbox" checked={confirm} disabled={dirty||busy} onChange={e=>setConfirm(e.target.checked)}/><span>Revisei o anúncio e confirmo a autorização para divulgar estas informações e fotografias.</span></label>}<button className="ps-button ps-button--primary" disabled={busy||dirty||(!item.published&&(!confirm||!!item.blockers.length))} onClick={()=>publish(item.published?'unpublish':'publish')}>{item.published?'Retirar do catálogo':'Publicar anúncio'}</button>{item.published&&<a className="ps-text-button" href={'/#/imovel/'+item.id} target="_blank" rel="noopener noreferrer">Abrir anúncio<ExternalLink size={15}/></a>}</>}</section>}
 </>}
 </div>;
}
