import { profilesFor } from '../../shared/locations.mjs';
import {preparePhoto} from './preparePhoto';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {ArrowLeft,ArrowRight,ArrowUp,ArrowDown,Plus,ExternalLink,Trash2,Check,House,LockKeyhole,Camera,ClipboardCheck,Copy} from 'lucide-react';
import {photoQualityIssue,photoPublicationIssues} from '../../shared/photo-policy.mjs';
import {api,ApiError,type TeamUser,type CaseDetails} from './api';
import {emptyDraft,listingTypes,photoRooms,type Draft,type Listing,type Photo} from './listingModel';
import './listings.css';

const steps=[
 {name:'Origem e imóvel',detail:'Identificação e dados reservados'},
 {name:'Características',detail:'Áreas, valores e condições'},
 {name:'Apresentação',detail:'O olhar editorial da EME'},
 {name:'Percurso de fotos',detail:'Uma sequência para explorar'},
 {name:'Revisão',detail:'Conferência e curadoria'},
];
const money=(value:number|null)=>value===null?'A confirmar':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(value);

export default function ListingsWorkspace({user}:{user:TeamUser}){
 const [items,setItems]=useState<Listing[]>([]),[item,setItem]=useState<Listing|null>(null),[editing,setEditing]=useState(false),[draft,setDraft]=useState<Draft>({...emptyDraft}),[photos,setPhotos]=useState<Photo[]>([]),[evaluationId,setEvaluationId]=useState<string>();
 const [step,setStep]=useState(0),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[dirty,setDirty]=useState(false),[confirm,setConfirm]=useState(false),[uploadProgress,setUploadProgress]=useState('');
 const submissionUrl=new URL('/enviar-imovel',location.origin).href;
 const fileInput=useRef<HTMLInputElement>(null),stepHeading=useRef<HTMLHeadingElement>(null),stepNav=useRef<HTMLElement>(null);
 const load=()=>api<{listings:Listing[]}>('/listings').then(r=>setItems(r.listings));
 useEffect(()=>{
  let active=true;
  load().catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});
  const query=new URLSearchParams(location.search),id=query.get('imovel')||query.get('avaliacao');
  if(id){(async()=>{try{const existing=await api<Listing>('/listings/'+encodeURIComponent(id));if(active){accept(existing);setEditing(true);}}catch(e){if(!(e instanceof ApiError)||e.status!==404||!query.get('avaliacao'))throw e;const r=await api<CaseDetails>('/evaluations/'+encodeURIComponent(id));if(active){setEvaluationId(id);setDraft({...emptyDraft,title:r.evaluation.title,city:r.evaluation.city,type:r.evaluation.type,ownerName:r.evaluation.owner,operation:r.evaluation.operation==='Locação'?'alugar':'comprar'});setEditing(true);setDirty(true);}}})().catch(e=>{if(active)setError(e.message);});}
  return()=>{active=false;};
 },[]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 useEffect(()=>{const nav=stepNav.current,active=nav?.querySelector<HTMLElement>('[aria-current=step]');if(nav&&active)nav.scrollLeft=active.offsetLeft-nav.offsetLeft-(nav.clientWidth-active.offsetWidth)/2;},[step,editing]);
 function accept(value:Listing){setItem(value);setDraft({...emptyDraft,...value.draft});setPhotos(value.photos);setDirty(false);setConfirm(false);setItems(old=>[value,...old.filter(x=>x.id!==value.id)]);}
 function edit(value:Listing|null){setError('');setMessage('');setEvaluationId(undefined);setConfirm(false);setItem(value);setDraft({...emptyDraft,...value?.draft});setPhotos(value?.photos||[]);setStep(0);setEditing(true);setDirty(!value);}
 function field<K extends keyof Draft>(key:K,value:Draft[K]){setDraft(prev=>({...prev,[key]:value}));setDirty(true);setConfirm(false);}
 function photoField(id:string,key:'caption'|'room',value:string){setPhotos(prev=>prev.map(p=>p.id===id?{...p,[key]:value}:p));setDirty(true);setConfirm(false);}
 function goTo(next:number){setStep(next);setMessage('');requestAnimationFrame(()=>{stepHeading.current?.focus({preventScroll:true});stepHeading.current?.scrollIntoView({block:'start'});});}
 async function save(e:FormEvent){
  e.preventDefault();
  if(!draft.title.trim()||!draft.city.trim()){setError('Informe o título e a cidade para salvar o rascunho. Os demais campos podem ser completados depois.');goTo(0);return;}
  setBusy(true);setError('');setMessage('');
  try{const result=await api<Listing>(item?'/listings/'+item.id:'/listings',item?'PATCH':'POST',item?{version:item.version,draft,photos:photos.map(({id,caption,room})=>({id,caption,room:room||''}))}:{draft,...(evaluationId?{evaluationId}:{})});accept(result);setMessage('Cadastro salvo. Continue pelas fotografias e pela curadoria.');}
  catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 async function upload(files:File[]){
  if(!item||!files.length)return;setError('');setMessage('');setBusy(true);let current=item;
  try{if(files.length+photos.length>20)throw Error('Cada imóvel pode ter até 20 fotografias.');for(let i=0;i<files.length;i++){const file=files[i];if(file.size>8*1024*1024)throw Error(file.name+': limite de 8 MB por foto.');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error(file.name+': use JPEG, PNG ou WebP.');setUploadProgress('Preparando foto '+(i+1)+' de '+files.length+'…');const content=await preparePhoto(file);current=await api<Listing>('/listings/'+current.id+'/photos','POST',{version:current.version,content,caption:''});accept(current);}setMessage('Fotografias salvas. Descreva cada ambiente e escolha a ordem da galeria.');}
  catch(e){setError((e as Error).message+' As fotos já concluídas foram preservadas.');}finally{setBusy(false);setUploadProgress('');if(fileInput.current)fileInput.current.value='';}
 }
 function move(index:number,direction:number){const next=[...photos];[next[index],next[index+direction]]=[next[index+direction],next[index]];setPhotos(next);setDirty(true);setConfirm(false);}
 async function publish(action:'publish'|'unpublish'){if(!item)return;setBusy(true);setError('');try{const value=await api<Listing>('/listings/'+item.id+'/'+action,'POST',{version:item.version,confirmed:confirm});accept(value);setMessage(action==='publish'?'Anúncio publicado na coleção EME.':'Anúncio retirado do catálogo.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function copySubmissionLink(){try{await navigator.clipboard.writeText(submissionUrl);setMessage('Link de envio copiado. Cada envio cria uma solicitação privada para avaliação.');}catch{setMessage('Copie o endereço do link de envio abaixo: '+submissionUrl);}}
 const textField=(label:string,key:keyof Draft,required=false)=><label>{label}<input required={required} maxLength={1200} value={String(draft[key]??'')} onChange={e=>field(key,e.target.value as never)}/></label>;
 const numField=(label:string,key:keyof Draft,increment='0.01')=><label>{label}<input type="number" min="0" step={increment} value={draft[key]??''} onChange={e=>field(key,(e.target.value===''?null:Number(e.target.value)) as never)}/></label>;
 const selectField=(label:string,key:keyof Draft,options:string[])=><label>{label}<select value={String(draft[key]??'')} onChange={e=>field(key,e.target.value as never)}><option value="">Não informado</option>{draft[key]&&!options.includes(String(draft[key]))&&<option>{String(draft[key])}</option>}{options.map(value=><option key={value}>{value}</option>)}</select></label>;
 const photoReady=photos.filter(p=>p.caption.trim().length>=3&&p.room).length;
 const photoIssues=photoPublicationIssues(photos);
 const photoQualityReady=photos.filter(p=>!photoQualityIssue(p)).length;
 const checks=[
  {title:'Identificação',detail:draft.title&&draft.city?'Título e cidade preenchidos':'Informe título e cidade',ready:!!draft.title.trim()&&!!draft.city.trim(),step:0},
  {title:'Dados do anúncio',detail:draft.price&&draft.area&&draft.neighborhood?'Preço, área e região informados':'Confira preço, área e região pública',ready:!!draft.price&&!!draft.area&&!!draft.neighborhood.trim(),step:1},
  {title:'Apresentação',detail:draft.description.trim().length>=80&&draft.reasons.trim()?'Descrição e diferenciais preenchidos':'Complete a descrição e os diferenciais',ready:draft.description.trim().length>=80&&!!draft.reasons.trim(),step:2},
  {title:'Percurso de fotos',detail:photos.length?photoIssues.length?photoIssues[0]:'Fotos identificadas e resolução mínima atendida':'Adicione as fotografias do imóvel',ready:photos.length>0&&!photoIssues.length,step:3},
 ];
 return <div className="pl-workspace">{error&&<div className="pt-error" role="alert">{error}</div>}{message&&<p className="pc-success" role="status">{message}</p>}
 {!editing?<>
  <div className="pl-intro"><div><h2>Imóveis da EME</h2><p>Da primeira informação a uma apresentação com identidade.</p></div><button className="ps-button ps-button--primary" onClick={()=>edit(null)}><Plus size={17}/>Cadastrar imóvel</button></div>
  <div className="pl-submission-link"><div><strong>Receba o imóvel pelo cliente.</strong><p>Compartilhe a ficha pública. O envio fica privado em Recebidos, para a equipe avaliar.</p><a href={submissionUrl} target="_blank" rel="noopener noreferrer">Abrir ficha de envio<ExternalLink size={13}/></a></div><button className="ps-button" onClick={copySubmissionLink}><Copy size={16}/>Copiar link de envio</button></div>
  {loading?<p role="status">Carregando imóveis…</p>:items.length?<div className="pl-list">{items.map(value=><button className="pl-list-item" key={value.id} onClick={()=>edit(value)}>{value.photos[0]?<img src={value.photos[0].url} alt=""/>:<span className="pl-no-photo"><House size={25}/></span>}<span><strong>{value.draft.title}</strong><small>{value.draft.city} · {value.draft.type}</small><em>{value.published?'Publicado':value.stage} · {value.photos.length} fotos</em></span><ArrowRight size={18}/></button>)}</div>:<div className="ps-card ps-empty"><House size={32}/><h3>Um lugar real. Uma apresentação à altura.</h3><p>Comece pelo que você já sabe. Complete a ficha e organize as fotos antes de encaminhar à curadoria.</p><button className="ps-button" onClick={()=>edit(null)}>Cadastrar primeiro imóvel</button></div>}
 </>:<>
  <div className="pl-editor-top"><button className="ps-text-button" disabled={busy} onClick={()=>{if(dirty&&!window.confirm('Sair sem salvar as alterações deste cadastro?'))return;setEditing(false);setDirty(false);load().catch(e=>setError(e.message));}}><ArrowLeft size={17}/>Todos os imóveis</button><span className="ps-tag">{item?(item.published?'Publicado':item.stage):'Novo cadastro'}</span>{item&&<a className="ps-button" href={'/portalselect/previa/'+item.id} target="_blank" rel="noopener noreferrer">Ver prévia salva<ExternalLink size={15}/></a>}</div>
  <div className="pl-dossier-heading"><div><span className="ps-overline">FICHA DO IMÓVEL</span><h2>{draft.title||'Um novo lugar na EME.'}</h2><p>Preencha no seu ritmo. O rascunho permanece privado até a aprovação e a publicação.</p></div><span className="pl-dossier-count"><strong>{String(step+1).padStart(2,'0')}</strong> / 05</span></div>
  <nav ref={stepNav} className="pl-steps" aria-label="Etapas do cadastro">{steps.map((entry,index)=><button key={entry.name} type="button" disabled={busy} aria-current={step===index?'step':undefined} onClick={()=>goTo(index)}><span>{String(index+1).padStart(2,'0')}</span><strong>{entry.name}</strong><small>{entry.detail}</small></button>)}</nav>
  <form className="ps-form pl-editor" onSubmit={save} noValidate>
   <fieldset disabled={busy} className="pc-fieldset">
    <section className="ps-card pl-step-card">
     <div className="pl-step-heading"><span className="ps-overline">{String(step+1).padStart(2,'0')} / {steps[step].name.toUpperCase()}</span><h2 ref={stepHeading} tabIndex={-1}>{['A história começa com informações claras.','Cada detalhe ajuda a escolher.','Conte o que torna este lugar especial.','Um percurso que faz sentido.','Confira antes de apresentar.'][step]}</h2></div>
     {step===0&&<>
      <p className="pc-help">Título e cidade são suficientes para iniciar. Tudo o que ainda não foi confirmado pode ficar em branco.</p>
      <div className="pl-fields">{textField('Título do anúncio','title',true)}{textField('Cidade e estado','city',true)}{textField('Bairro ou região pública','neighborhood')}<label>Tipo<select value={draft.type} onChange={e=>{field('type',e.target.value);if(e.target.value==='Casa em condomínio')field('condominium','horizontal');}}>{listingTypes.map(type=><option key={type}>{type}</option>)}</select></label><label>Ambiente<select value={draft.environment} onChange={e=>{field('environment',e.target.value as Draft['environment']);field('locationProfile','');}}>{[['urbano','Urbano'],['litoral','Litoral'],['serra','Serra'],['comercial','Comercial'],['terrenos','Terrenos'],['industrial','Industrial']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Localização no ambiente<select value={draft.locationProfile||''} onChange={e=>field('locationProfile',e.target.value)}>{profilesFor(draft.environment).map(p=><option key={p.value} value={p.value}>{p.value?p.label:'Não informado'}</option>)}</select></label><label>Condomínio<select value={draft.condominium} onChange={e=>field('condominium',e.target.value as Draft['condominium'])}><option value="">Não informado / não se aplica</option><option value="horizontal">Horizontal</option><option value="vertical">Vertical</option></select></label></div>
      <p className="pc-help">A localização pública deve indicar apenas a região. Endereço completo e contatos ficam na área reservada abaixo.</p>
      <div className="pl-reserved"><div className="pl-subheading"><LockKeyhole size={17}/><div><h3>Origem e informações reservadas</h3><p>Somente a equipe EME. Estes dados não aparecem no anúncio.</p></div></div><div className="pl-fields">{textField('Fonte ou canal de origem','sourceName')}{textField('Link do anúncio de origem','sourceUrl')}{textField('Código na fonte original','sourceReference')}{selectField('Vínculo de quem enviou','requesterRole',['Proprietário','Representante do proprietário','Corretor parceiro','Equipe EME','A confirmar'])}{textField('Nome de quem enviou · privado','ownerName')}{textField('Contato de quem enviou · privado','ownerContact')}</div>{textField('Endereço completo · privado','privateAddress')}<label>Observações da fonte e pontos a confirmar<textarea rows={4} maxLength={1200} value={draft.sourceNotes} onChange={e=>field('sourceNotes',e.target.value)} placeholder="Registre de onde vieram as informações, quando foram consultadas e o que precisa de confirmação."/></label><div className="pl-fields">{selectField('Documentação recebida','documentationStatus',['Pendente','Parcialmente recebida','Recebida','Em revisão'])}{selectField('Autorização para divulgação','authorizationStatus',['Pendente','Solicitada','Recebida','Não autorizada'])}</div><p className="pc-help">Receber documentos ou uma autorização não equivale a aprovar o imóvel. As conferências e a decisão ficam registradas na curadoria.</p></div>
     </>}
     {step===1&&<>
      <div className="pl-fields"><label>Finalidade<select value={draft.operation} onChange={e=>field('operation',e.target.value as Draft['operation'])}><option value="comprar">Venda</option><option value="alugar">Locação</option></select></label>{numField(draft.operation==='alugar'?'Aluguel mensal (R$)':'Preço de venda (R$)','price')}{numField('Área privativa ou útil (m²)','area')}{numField('Área total (m²)','totalArea')}{numField('Quartos','bedrooms','1')}{numField('Suítes','suites','1')}{numField('Banheiros','bathrooms','1')}{numField('Vagas','parking','1')}{numField('Ano de construção','yearBuilt','1')}{selectField('Situação de ocupação','occupancy',['Desocupado','Ocupado pelo proprietário','Locado','Locação de temporada','Em construção','A confirmar'])}{numField('Condomínio mensal (R$)','condominiumFee')}{numField('IPTU anual (R$)','propertyTax')}</div>
      {textField('Observações sobre despesas e área','costNotes')}
      <p className="pc-help">Deixe vazio o que não foi informado. Zero significa ausência confirmada. Diferencie a área privativa da área total e confirme a periodicidade das despesas.</p>
     </>}
     {step===2&&<>
      <p className="pc-help">Apresente os espaços e o entorno com precisão. Informações do anúncio de origem ainda precisam ser conferidas pela equipe.</p>
      <label>Descrição do imóvel<textarea rows={7} maxLength={5000} value={draft.description} onChange={e=>field('description',e.target.value)} placeholder="Descreva os ambientes, a integração dos espaços, a luz e as características conhecidas. Separe fatos confirmados de informações a verificar."/><small className="pl-character-count">{draft.description.length} / 5.000 caracteres · mínimo de 80 para publicar</small></label>
      <div className="pl-fields"><label>Características · uma por linha<textarea rows={5} maxLength={1200} value={draft.features} onChange={e=>field('features',e.target.value)} placeholder={'Sala integrada à varanda\nCozinha com bancada\nDuas vagas de garagem'}/></label><label>Diferenciais EME · um por linha<textarea rows={5} maxLength={1200} value={draft.reasons} onChange={e=>field('reasons',e.target.value)} placeholder={'Vista aberta a partir da área social\nIntegração entre estar e jantar\nPlanta que favorece a convivência'}/></label></div>
      <div className="pl-editor-note"><ClipboardCheck size={20}/><p>Use a ficha para descrever o imóvel. Reserve afirmações sobre regularidade documental, exclusividade ou rentabilidade para quando houver comprovação.</p></div>
     </>}
     {step===3&&<>
      <p className="pc-help">A primeira foto será a capa e a abertura do percurso. Depois, aproxime quem visita dos ambientes em uma ordem natural, sem repetir ângulos muito parecidos.</p>
      <div className="pl-photo-guide"><Camera size={23}/><div><strong>Uma sequência, uma história.</strong><p>Área social → cozinha → área íntima → serviço → condomínio. Adapte a ordem ao imóvel e identifique cada ambiente.</p></div></div>
      <div className="pl-quality-guide"><h3>O padrão começa no arquivo original.</h3><p>Para publicar: lado maior com pelo menos <strong>2000 px</strong> e lado menor com <strong>1200 px</strong>. Prefira originais de 3000 px ou mais e uma capa horizontal. Fotos menores podem ficar no rascunho, mas precisam ser substituídas antes da divulgação.</p><ul><li>Envie o arquivo da câmera. Evite capturas de tela e fotos comprimidas pelo WhatsApp.</li><li>Limpe a lente, use luz natural e mantenha as linhas verticais retas. Evite zoom digital e grande angular que distorça os ambientes.</li><li>Mostre todos os espaços relevantes, incluindo conservação e limitações. Não remova defeitos com edição.</li><li>Organize o percurso sem ângulos repetidos. Identifique cada cômodo nas legendas e separe a área privativa das áreas comuns.</li></ul><p className="pl-quality-note">Resolução é uma verificação técnica. Nitidez, exposição, fidelidade e autorização de uso também precisam da conferência da equipe.</p></div>
      <div className="pl-upload"><div><strong>Adicionar fotografias reais</strong><p>Até 20 imagens JPEG, PNG ou WebP · até 8 MB cada.</p></div><input ref={fileInput} className="pl-file" type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={!item||dirty||busy} aria-label="Adicionar fotografias do imóvel" onChange={e=>upload(Array.from(e.target.files||[]))}/></div>
      {!item||dirty?<p className="pc-help">Salve o cadastro antes de adicionar fotos.</p>:<p className="pc-help">Use fotografias autorizadas. As imagens são preparadas para a tela; a próxima só aparece depois de estar carregada.</p>}
      {uploadProgress&&<p role="status">{uploadProgress}</p>}
      {!!photos.length&&<div className="pl-photo-summary"><span>{photos.length} {photos.length===1?'fotografia':'fotografias'} no percurso</span><span>{photoReady} com ambiente e legenda · {photoQualityReady} com resolução mínima</span></div>}
      <div className="pl-photo-grid">{photos.map((photo,index)=><article className="pl-photo" key={photo.id}><div><img src={photo.url} alt={photo.caption||'Foto aguardando descrição'}/><span>{index===0?'01 · Capa':String(index+1).padStart(2,'0')}</span></div><p className={photoQualityIssue(photo)?"pl-photo-quality is-pending":"pl-photo-quality"}>{photo.width} × {photo.height} px · {photoQualityIssue(photo)||"Resolução mínima atendida"}</p>{index===0&&photo.width<photo.height&&<p className="pl-photo-quality is-pending">Escolha uma foto horizontal para a capa.</p>}<label>Grupo da foto {index+1}<select value={photo.room||''} onChange={e=>photoField(photo.id,'room',e.target.value)}><option value="">Escolha o ambiente</option>{photo.room&&!photoRooms.includes(photo.room)&&<option value={photo.room}>{photo.room}</option>}{photoRooms.map(room=><option key={room}>{room}</option>)}</select></label><label>Legenda da foto {index+1}<input value={photo.caption} maxLength={180} placeholder="Ex.: sala de estar em direção à varanda" onChange={e=>photoField(photo.id,'caption',e.target.value)}/></label><div className="pl-photo-tools"><button type="button" className="ps-icon" disabled={!index} aria-label={'Mover foto '+(index+1)+' para antes'} onClick={()=>move(index,-1)}><ArrowUp size={16}/></button><button type="button" className="ps-icon" disabled={index===photos.length-1} aria-label={'Mover foto '+(index+1)+' para depois'} onClick={()=>move(index,1)}><ArrowDown size={16}/></button><button type="button" className="ps-text-button" onClick={()=>{setPhotos(prev=>prev.filter(value=>value.id!==photo.id));setDirty(true);setConfirm(false);}}><Trash2 size={14}/>Remover</button></div></article>)}</div>
      {!photos.length&&<div className="pl-empty-photos"><Camera size={30}/><p>O percurso começa com uma boa fotografia.</p><small>Salve a ficha e adicione as imagens para organizar a visita.</small></div>}
     </>}
     {step===4&&<>
      <div className="pl-review-cover">{photos[0]?<img src={photos[0].url} alt={photos[0].caption||'Capa do imóvel'}/>:<span className="pl-review-placeholder"><House size={35}/></span>}<div><span className="ps-overline">{draft.type} · {draft.operation==='alugar'?'LOCAÇÃO':'VENDA'}</span><h3>{draft.title||'Título a preencher'}</h3><p>{[draft.neighborhood,draft.city].filter(Boolean).join(' · ')||'Localização a preencher'}</p><strong>{money(draft.price)}{draft.operation==='alugar'&&draft.price!==null?' / mês':''}</strong><small>{draft.area===null?'Área a confirmar':draft.area+' m² privativos / úteis'} · {photos.length} fotos</small></div></div>
      <div className="pl-review-checks">{checks.map(check=><button type="button" key={check.title} onClick={()=>goTo(check.step)}><span className={check.ready?'is-complete':''}>{check.ready?<Check size={15}/>:String(check.step+1).padStart(2,'0')}</span><div><strong>{check.title}</strong><small>{check.detail}</small></div><ArrowRight size={17}/></button>)}</div>
      <p className="pc-help">Este resumo indica o preenchimento da ficha, não a aprovação do imóvel. Confira as informações e as fotos na prévia salva antes de seguir para a curadoria.</p>
      {dirty&&<div className="pl-editor-note"><ClipboardCheck size={20}/><p>Existem alterações não salvas. Salve o rascunho para atualizar a prévia e os pontos pendentes abaixo.</p></div>}
     </>}
    </section>
   </fieldset>
   <div className="pl-save"><div className="pl-save-status"><button className="ps-button ps-button--primary" disabled={busy||!dirty}><Check size={17}/>{busy?'Salvando…':'Salvar cadastro'}</button><small>{dirty?'Rascunho com alterações não salvas':'Versão salva no portal'}</small></div><div className="pl-step-actions">{step>0&&<button type="button" className="ps-button" disabled={busy} onClick={()=>goTo(step-1)}><ArrowLeft size={16}/>Anterior</button>}{step<steps.length-1&&<button type="button" className="ps-button" disabled={busy} onClick={()=>goTo(step+1)}>Continuar<ArrowRight size={16}/></button>}</div></div>
  </form>
  {step===4&&(item?<section className="ps-card pl-publish"><span className="ps-overline">CURADORIA E PUBLICAÇÃO</span><h2>Uma decisão consciente, antes de entrar na coleção.</h2>{item.blockers.length>0?<div className="pl-pending"><strong>Pontos pendentes na versão salva</strong><ul>{item.blockers.map(value=><li key={value}>{value}</li>)}</ul></div>:<p className="pc-help">A versão salva atende aos requisitos de publicação. A divulgação ainda depende da confirmação do administrador.</p>}<a className="ps-button" href={'/portalselect/avaliacoes?imovel='+item.id}>Abrir curadoria<ArrowRight size={16}/></a><p className="pc-help">Alterar dados ou fotos retira uma publicação anterior e exige nova conferência da curadoria. A prévia usa a versão salva. Após a publicação, o anúncio fica disponível na coleção conectada a este portal.</p>{user.role==='admin'&&<>{!item.published&&<label className="pl-confirm"><input type="checkbox" checked={confirm} disabled={dirty||busy} onChange={e=>setConfirm(e.target.checked)}/><span>Revisei o anúncio e confirmo a autorização para divulgar estas informações e fotografias.</span></label>}<button className="ps-button ps-button--primary" disabled={busy||dirty||(!item.published&&(!confirm||!!item.blockers.length))} onClick={()=>publish(item.published?'unpublish':'publish')}>{item.published?'Retirar do catálogo':'Publicar anúncio'}</button>{item.published&&<a className="ps-text-button" href={'/#/imovel/'+item.id} target="_blank" rel="noopener noreferrer">Abrir anúncio<ExternalLink size={15}/></a>}</>}</section>:<div className="pl-editor-note"><ClipboardCheck size={20}/><p>Salve o rascunho para abrir a curadoria e acompanhar as pendências deste imóvel.</p></div>)}
 </>}
 </div>;
}
