import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { Check, FileText, Plus, ShieldCheck, X } from 'lucide-react';

export type OperationOption = { value: string; label: string };
export type OperationField = { key: string; label: string; type?: 'text'|'email'|'tel'|'date'|'datetime-local'|'month'|'number'|'textarea'|'select'; options?: OperationOption[]; value?: string|number|null; required?: boolean; requiredWhen?: (values: OperationValues) => boolean; help?: string; full?: boolean; min?: string; max?: string; step?: string; maxLength?: number };
export type OperationValues = Record<string, string>;
export const operationToday = () => new Date().toLocaleDateString('en-CA', { timeZone: 'America/Sao_Paulo' });
export const operationDate = (value?: string|null) => value ? value.slice(0, 10).split('-').reverse().join('/') : 'Não informado';
export const operationTimestamp = (value?: string|null) => value ? new Date(value).toLocaleString('pt-BR', { dateStyle: 'short', timeStyle: 'short', timeZone: 'America/Sao_Paulo' }) : 'Não informado';
export const operationMoney = (value: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value / 100);
export const operationAmount = (value: string) => Math.round(Number(value.replace(',', '.')) * 100);
export const localTimestamp = (value?: string|null) => value ? new Date(new Date(value).getTime() - new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,23) : '';

export function OperationModal({ title, description, children, onClose, busy = false }: { title: string; description?: string; children: ReactNode; onClose: () => void; busy?: boolean }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const previous = document.activeElement as HTMLElement; const overflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; ref.current?.showModal(); return () => { document.body.style.overflow = overflow; if (previous?.isConnected) previous.focus(); }; }, []);
  return <dialog ref={ref} className="po-modal" aria-label={title} onCancel={event => { event.preventDefault(); if (!busy) onClose(); }}><header><div><span className="ps-overline">EME SELECT · OPERAÇÃO</span><h2>{title}</h2></div><button className="ps-icon" disabled={busy} aria-label="Fechar formulário" onClick={onClose}><X size={20}/></button></header><div className="po-modal-body">{description && <p className="po-form-description">{description}</p>}{children}</div></dialog>;
}

export function OperationForm({ fields, onSubmit, onClose, onReload, submitLabel = 'Salvar registro', children }: { fields: OperationField[]; onSubmit: (values: OperationValues) => Promise<void>; onClose: () => void; onReload: () => Promise<boolean>; submitLabel?: string; children?: ReactNode }) {
  const [values, setValues] = useState<OperationValues>(() => Object.fromEntries(fields.map(field => [field.key, String(field.value ?? '')])));
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); setNotice(''); try { await onSubmit(values); } catch (issue) { setError((issue as Error).message); } finally { setBusy(false); } }
  return <form className="po-form" onSubmit={submit}><fieldset disabled={busy}><div className="po-form-grid">{fields.map((field, index) => <label key={field.key} className={field.full ? 'po-field-full' : undefined}>{field.label}{field.type === 'select' ? <select aria-label={field.label} required={field.requiredWhen ? field.requiredWhen(values) : field.required !== false} value={values[field.key]} onChange={event => setValues(previous => ({ ...previous, [field.key]: event.target.value }))}><option value="">{field.required === false ? 'Não informado / sem vínculo' : 'Selecione'}</option>{field.options?.map(option => <option value={option.value} key={option.value}>{option.label}</option>)}</select> : field.type === 'textarea' ? <textarea aria-label={field.label} required={field.requiredWhen ? field.requiredWhen(values) : field.required !== false} rows={4} maxLength={field.maxLength ?? 2000} value={values[field.key]} onChange={event => setValues(previous => ({ ...previous, [field.key]: event.target.value }))}/> : <input aria-label={field.label} autoFocus={index === 0} type={field.type ?? 'text'} required={field.requiredWhen ? field.requiredWhen(values) : field.required !== false} min={field.min} max={field.max} step={field.step ?? (field.type === 'number' ? '0.01' : field.type === 'datetime-local' ? '0.001' : undefined)} maxLength={field.maxLength ?? 160} value={values[field.key]} onChange={event => setValues(previous => ({ ...previous, [field.key]: event.target.value }))}/>} {field.help && <small>{field.help}</small>}</label>)}</div>{children}</fieldset>{error && <div className="pt-error" role="alert"><p>{error}</p><button type="button" className="ps-text-button" disabled={busy} onClick={async () => { setBusy(true); if (await onReload()) { setError(''); setNotice('Dados atualizados. Seus campos foram preservados; confira e salve novamente.'); } setBusy(false); }}>Atualizar dados sem perder os campos</button></div>}{notice && <p className="po-form-notice" role="status">{notice}</p>}<footer><button type="button" className="ps-button" disabled={busy} onClick={onClose}>Cancelar</button><button className="ps-button ps-button--primary" disabled={busy}>{busy ? 'Salvando…' : submitLabel}<Check size={16}/></button></footer></form>;
}

export function OperationEmpty({ title, description, action, onAction }: { title: string; description: string; action?: string; onAction?: () => void }) { return <div className="po-empty"><FileText size={27}/><h3>{title}</h3><p>{description}</p>{action && <button className="ps-button ps-button--primary" onClick={onAction}><Plus size={16}/>{action}</button>}</div>; }
export function OperationNotice({ children }: { children: ReactNode }) { return <div className="po-notice"><ShieldCheck size={17}/><p>{children}</p></div>; }
export function OperationStat({ label, value, note }: { label: string; value: string|number; note?: string }) { return <div className="po-stat"><span>{label}</span><strong>{value}</strong>{note && <small>{note}</small>}</div>; }
