import {useEffect,useRef,useState} from 'react';
import {Dialog} from '../ui';
import {enhancePhoto} from './photoEnhancer';
import {preparePhoto} from './preparePhoto';
import type {Photo} from './listingModel';
import './photo-studio.css';
export default function PhotoStudio({photo,onClose,onSave}:{photo:Photo;onClose:()=>void;onSave:(content:string)=>Promise<void>}){
 const [result,setResult]=useState(''),[progress,setProgress]=useState(0),[busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[checked,setChecked]=useState(false),[zoom,setZoom]=useState(false);const controller=useRef<AbortController|null>(null);
 useEffect(()=>()=>controller.current?.abort(),[]);
 async function enhance(){setBusy(true);setError('');setProgress(0);controller.current=new AbortController();try{const image=new Image();image.src=photo.url;await image.decode();if(image.naturalWidth*image.naturalHeight>4000000)throw Error('Esta foto já é grande. Use o original; a ampliação é destinada a fotos de até 4 megapixels.');const raw=await enhancePhoto(photo.url,setProgress,controller.current.signal);if(controller.current.signal.aborted)return;const blob=await(await fetch(raw)).blob();setResult(await preparePhoto(new File([blob],'eme-ampliada.png',{type:'image/png'}),true));setChecked(false);}catch(e){setError(controller.current?.signal.aborted?'Preparação cancelada. O original está preservado.':(e as Error).message);}finally{setBusy(false);}}
 async function save(){setSaving(true);setError('');try{await onSave(result);onClose();}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 return <Dialog title="Ateliê de fotografias" onClose={()=>{if(!saving){controller.current?.abort();onClose();}}} wide><div className="photo-studio"><p>Amplie a resolução em 2× com IA. Compare texturas, linhas e detalhes antes de aplicar. O arquivo anterior permanece reservado à equipe. O processo pode levar alguns minutos neste dispositivo.</p><div className={'photo-studio-comparison'+(zoom?' is-zoom':'')}><figure><figcaption>Antes · {photo.width} × {photo.height} px</figcaption><div><img src={photo.url} alt="Fotografia antes da ampliação"/></div></figure><figure><figcaption>{result?'Depois · preparada para a galeria':'Sua versão preparada'}</figcaption><div>{result?<img src={result} alt="Fotografia ampliada para conferência"/>:<p>{busy?'Preparando a imagem…':'A ampliação aparecerá aqui.'}</p>}</div></figure></div><label><input type="checkbox" checked={zoom} onChange={e=>setZoom(e.target.checked)}/> Inspecionar detalhes em tamanho natural</label>{busy?<><progress max={100} value={progress}/><p role="status">{progress===0?'Carregando a ferramenta…':progress+'% · ampliando os detalhes'}</p><button className="ps-button" onClick={()=>controller.current?.abort()}>Cancelar processamento</button></>:<button className="ps-button" disabled={saving} onClick={enhance}>{result?'Refazer a partir da foto atual':'Preparar ampliação de 2×'}</button>}{error&&<p className="pt-error" role="alert">{error}</p>}{result&&<><label className="pl-confirm"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/> Comparei as imagens e confirmei que os detalhes e a conservação do imóvel continuam fiéis.</label><button className="ps-button ps-button--primary" disabled={!checked||busy||saving} onClick={save}>{saving?'Salvando…':'Usar a versão preparada'}</button></>}<p className="pc-help">A ampliação não garante recuperação de detalhes perdidos. Fotos verticais são apresentadas por inteiro, com margem, sem criar partes do ambiente. A publicação continua dependendo da curadoria.</p></div></Dialog>;
}
