import {useEffect,useRef,useState} from 'react';
import {Dialog} from '../ui';
import {enhancePhoto} from './photoEnhancer';
import type {Photo} from './listingModel';
import './photo-studio.css';
export default function PhotoStudio({photo,listingId,version,onClose,onSave}:{photo:Photo;listingId:string;version:number;onClose:()=>void;onSave:(content:string)=>Promise<void>}){
 const [result,setResult]=useState(''),[dimensions,setDimensions]=useState(''),[busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[checked,setChecked]=useState(false),[zoom,setZoom]=useState(false);const controller=useRef<AbortController|null>(null);
 useEffect(()=>()=>controller.current?.abort(),[]);
 async function enhance(){setBusy(true);setError('');controller.current=new AbortController();try{const prepared=await enhancePhoto(listingId,photo.id,version,controller.current.signal);if(controller.current.signal.aborted)return;setResult(prepared.content);setDimensions(prepared.width+' × '+prepared.height+' px');setChecked(false);}catch(e){setError(controller.current?.signal.aborted?'Preparação cancelada. O original está preservado.':(e as Error).message);}finally{setBusy(false);}}
 async function save(){setSaving(true);setError('');try{await onSave(result);onClose();}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 return <Dialog title="Ateliê de fotografias" onClose={()=>{if(!saving){controller.current?.abort();onClose();}}} wide><div className="photo-studio"><p>Prepare uma ampliação de até 2×, limitada a 3200 px, mantendo o enquadramento da foto. Compare o resultado antes de aplicar. O original permanece reservado no portal.</p><div className={'photo-studio-comparison'+(zoom?' is-zoom':'')}><figure><figcaption>Antes · {photo.width} × {photo.height} px</figcaption><div><img src={photo.url} alt="Fotografia antes da ampliação"/></div></figure><figure><figcaption>{result?'Depois · '+dimensions:'Sua versão preparada'}</figcaption><div>{result?<img src={result} alt="Fotografia ampliada para conferência"/>:<p>{busy?'Preparando a imagem…':'A ampliação aparecerá aqui.'}</p>}</div></figure></div><label><input type="checkbox" checked={zoom} onChange={e=>setZoom(e.target.checked)}/> Inspecionar detalhes em tamanho natural</label>{busy?<><progress aria-label="Preparando fotografia"/><p role="status">Preparando a fotografia no servidor…</p><button className="ps-button" onClick={()=>controller.current?.abort()}>Cancelar processamento</button></>:<button className="ps-button" disabled={saving} onClick={enhance}>{result?'Refazer a partir do original':'Preparar ampliação'}</button>}{error&&<p className="pt-error" role="alert">{error}</p>}{result&&<><label className="pl-confirm"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/> Comparei as imagens e confirmei que os detalhes e a conservação do imóvel continuam fiéis.</label><button className="ps-button ps-button--primary" disabled={!checked||busy||saving} onClick={save}>{saving?'Salvando…':'Usar a versão preparada'}</button></>}<p className="pc-help">Esta ampliação é convencional, sem IA: aumenta as dimensões do arquivo e não recupera detalhes perdidos. Para impressão, confira o tamanho final com a gráfica. Fotos verticais são apresentadas por inteiro, com margem, sem criar partes do ambiente. A publicação continua dependendo da curadoria.</p></div></Dialog>;
}
