import {lazy,Suspense,useState} from 'react';
import {ArrowDown,ArrowUp,Box,Download,Play,Sparkles} from 'lucide-react';
import {defaultScene,sceneAssets,sceneFinishes,sceneRooms,validateScene,type SpatialScene} from '../../shared/spatial-scene.mjs';
import {exportSpatialModel} from './spatial-export';
import '../developments/g400-residence.css';
import {presentationLink} from '../presentation/config';
const Model=lazy(()=>import('../developments/G400ApartmentModel'));
const base='/assets/developments/g400/';
export default function SpatialSceneBuilder({scene,onBuild,onAI,aiEnabled,busy,title='G400'}:{title?:string;scene?:SpatialScene|null;onBuild:(scene:SpatialScene)=>void;onAI:()=>void;aiEnabled:boolean;busy:boolean}){
 const [draft,setDraft]=useState<SpatialScene>(()=>scene||defaultScene()),[index,setIndex]=useState(0),[inside,setInside]=useState(false),[room,setRoom]=useState(scene?.room||'living'),[ready,setReady]=useState(false),[failed,setFailed]=useState(false),[exporting,setExporting]=useState(false),[error,setError]=useState('');
 const changed=JSON.stringify(scene)!==JSON.stringify(draft);
 function change<K extends keyof SpatialScene>(key:K,value:SpatialScene[K]){setDraft(p=>({...p,[key]:value}));}
 function toggle(id:string){change('assets',draft.assets.includes(id)?draft.assets.filter(a=>a!==id):[...draft.assets,id]);}
 function move(id:string,direction:number){const items=[...draft.assets],from=items.indexOf(id),to=from+direction;if(to<0||to>=items.length)return;[items[from],items[to]]=[items[to],items[from]];change('assets',items);}
 function build(){try{const config=validateScene(draft);onBuild(config);setIndex(0);setInside(false);setRoom(config.room);setFailed(false);setError('');}catch(e){setError((e as Error).message);}}
 const active=sceneAssets.find(a=>a.id===scene?.assets[index%scene.assets.length]);
 return <section className="ps-card spatial-builder"><span className="ps-overline">OFICINA DE CENÁRIOS / G400</span><h2>Monte. Explore. Refine.</h2><p>Escolha uma base, organize o percurso e monte uma versão para revisão. A configuração será salva junto com o projeto.</p>
  <div className="spatial-builder-layout"><div className="spatial-builder-controls ps-form">
   <label>Base do cenário<select value={draft.mode} onChange={e=>change('mode',e.target.value as SpatialScene['mode'])}><option value="presentation">Apresentação por imagens · G400</option><option value="tipo5">Apartamento Tipo 5 · piloto 3D</option></select></label>
   {draft.mode==='tipo5'&&<><label>Acabamento<select value={draft.finish} onChange={e=>change('finish',e.target.value)}>{sceneFinishes.map(f=><option key={f.id} value={f.id}>{f.label}</option>)}</select></label><label>Iluminação inicial<select value={draft.hour} onChange={e=>change('hour',Number(e.target.value))}><option value={14}>Dia</option><option value={18}>Entardecer</option><option value={21}>Noite</option>{![14,18,21].includes(draft.hour)&&<option value={draft.hour}>{draft.hour} h</option>}</select></label><label>Início da caminhada<select value={draft.room} onChange={e=>change('room',e.target.value)}>{sceneRooms.map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select></label></>}
   <p className="spatial-help">{draft.mode==='tipo5'?'Modelo conceitual da planta Tipo 5. Acabamentos são estudos; não representam o memorial aprovado.':'Perspectivas fornecidas do empreendimento. A navegação troca imagens; não é caminhada livre nem captura 360°.'}</p>
   <button className="ps-button ps-button--primary" disabled={busy||draft.assets.length<2} onClick={build}><Box size={16}/>{scene?'Atualizar cenário':'Montar cenário'}</button>
   <button className="ps-button" disabled={!aiEnabled||busy} onClick={onAI}><Sparkles size={16}/>{busy?'Preparando…':'Compor cenário com IA'}</button>
   <small>Para usar IA, salve o objetivo do projeto e ative a conexão na Central de IA. A solicitação envia o objetivo e as descrições do acervo, com possível custo de API.</small>
  </div><div className="spatial-builder-preview">
   {!scene?<div className="spatial-scene-empty"><Box size={40}/><h3>Sua primeira composição</h3><p>Selecione a base ao lado e clique em Montar cenário.</p><img src={base+'carousel-apartament-01.webp'} alt="Referência de interiores do G400"/></div>:scene.mode==='presentation'?<><div className="spatial-photo-stage"><img src={base+active?.file} alt={active?.label}/><div><small>VISITA POR IMAGENS · {index%scene.assets.length+1} / {scene.assets.length}</small><h3>{active?.label}</h3></div></div><nav className="spatial-scene-nav" aria-label="Percurso de apresentação">{scene.assets.map((id,i)=><button key={id} aria-pressed={i===index%scene.assets.length} onClick={()=>setIndex(i)}>{sceneAssets.find(a=>a.id===id)?.label}</button>)}</nav></>:<><div className="spatial-model-stage">{!failed&&<Suspense fallback={<p>Preparando visualização 3D…</p>}><Model room={room} inside={inside} hour={scene.hour} finish={scene.finish} reset={0} onEnter={()=>setInside(true)} onSelect={setRoom} onReady={()=>setReady(true)} onFail={()=>setFailed(true)}/></Suspense>}{failed&&<p role="alert">O 3D não está disponível neste dispositivo. As referências e a exportação continuam acessíveis.</p>}</div><div className="spatial-scene-nav"><button disabled={!ready||failed} onClick={()=>setInside(p=>!p)}><Play size={14}/>{inside?'Ver apartamento completo':'Entrar e caminhar'}</button>{inside&&sceneRooms.map(r=><button key={r.id} aria-pressed={room===r.id} onClick={()=>setRoom(r.id)}>{r.label}</button>)}</div><p className="spatial-help">Clique no piso para caminhar; arraste para olhar. Use também W, A, S, D ou as setas com o cenário em foco.</p><button className="ps-button" disabled={exporting||busy} onClick={async()=>{setExporting(true);setError('');try{await exportSpatialModel(scene);}catch{setError('Não foi possível exportar o modelo. Tente novamente.');}finally{setExporting(false);}}}><Download size={16}/>{exporting?'Preparando modelo…':'Baixar modelo 3D (.glb)'}</button></>}
   {scene&&changed&&<p className="spatial-notice">Existem ajustes na oficina. Clique em Atualizar cenário para aplicá-los à visualização.</p>}
  </div></div>
  {error&&<p role="alert" className="pt-error">{error}</p>}
  <section className="spatial-delivery"><h3>Apresente em qualquer tela.</h3><p>Link direto para TV, tela touch ou notebook. Sem login e sem dados internos do projeto.</p><div className="spatial-document-actions"><a className="ps-button" href="/apresentar/g400" target="_blank" rel="noreferrer">Apresentar empreendimento G400 ↗</a>{scene&&<><a className="ps-button ps-button--primary" href={presentationLink(title,scene)} target="_blank" rel="noreferrer">Abrir este cenário em apresentação ↗</a><button className="ps-button" onClick={async()=>{try{await navigator.clipboard.writeText(presentationLink(title,scene));setError('Link da versão atual copiado.');}catch{setError('Abra a apresentação e copie o endereço do navegador.');}}}>Copiar link para o cliente</button></>}</div><p className="spatial-help">O link deste cenário contém apenas título, imagens e ajustes visuais. É uma cópia da configuração atual: alterações futuras exigem um novo link. Quem receber pode abrir e encaminhar. Nesta versão, não há revogação nem edição pelo cliente.</p></section>
  <h3>Acervo e ordem da visita</h3><p>Escolha pelo menos duas referências. A ordem abaixo define o percurso da apresentação e a primeira imagem será a capa do PDF.</p>
  <div className="spatial-asset-grid">{sceneAssets.map(a=><label key={a.id}><img src={base+a.file} alt="" loading="lazy"/><span><input type="checkbox" checked={draft.assets.includes(a.id)} onChange={()=>toggle(a.id)}/>{a.label}</span></label>)}</div>
  <ol className="spatial-order">{draft.assets.map((id,i)=><li key={id}><span>{sceneAssets.find(a=>a.id===id)?.label}</span><button aria-label={'Mover '+id+' para cima'} disabled={i===0} onClick={()=>move(id,-1)}><ArrowUp size={15}/></button><button aria-label={'Mover '+id+' para baixo'} disabled={i===draft.assets.length-1} onClick={()=>move(id,1)}><ArrowDown size={15}/></button></li>)}</ol>
 </section>;
}
