import {useEffect,useState,lazy,Suspense} from 'react';
import {ArrowUpRight,Box,Download,Layers3,Save,Sparkles} from 'lucide-react';
import {api,ApiError} from './api';
import {initialSpatialProject,applySpatialScope,estimateSpatialProject,spatialLevels,type SpatialProject,type SpatialPlan} from '../../shared/spatial-studio.mjs';
import {defaultProposal,type SpatialScene} from '../../shared/spatial-scene.mjs';
import './spatial-studio.css';
const SceneBuilder=lazy(()=>import('./SpatialSceneBuilder'));
type Record={id:string;version:number;project:SpatialProject;updatedAt:string};
type Snapshot={projects:Record[];aiReady:boolean;productionReady:boolean;previewOnly?:boolean};
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
const initial=()=>applySpatialScope(initialSpatialProject(),'pilot');
const base='/assets/developments/g400/';
const refs=[['Edifício','carousel-apresentation-03.webp'],['Interiores','carousel-apartament-03.webp'],['Lazer','carousel-social-structure-02.webp'],['Planta Tipo 5','planta-tipo-5.webp']];
export default function SpatialStudio(){
 const [data,setData]=useState<Snapshot|null>(null),[project,setProject]=useState(initial),[record,setRecord]=useState<Record|null>(null);
 const [tab,setTab]=useState('project'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[dirty,setDirty]=useState(false);
 const [reload,setReload]=useState(0),[sceneRevision,setSceneRevision]=useState(0);
 const proposal={...defaultProposal(),...project.proposal};
 useEffect(()=>{let active=true;api<Snapshot>('/spatial-studio').then(x=>{if(active)setData(x);}).catch(e=>{if(active){setError(e.message);if(e instanceof ApiError && (e.status>=500||e.status===0)){setData({projects:[],aiReady:false,productionReady:false,previewOnly:true});}}});return()=>{active=false;};},[reload]);
 useEffect(()=>{if(!dirty)return;const prevent=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent);},[dirty]);
 let estimate:ReturnType<typeof estimateSpatialProject>|null=null;try{estimate=estimateSpatialProject(project);}catch{}
 function update<K extends keyof SpatialProject>(key:K,value:SpatialProject[K]){setProject(p=>({...p,[key]:value,...(key!=='plan'?{plan:null}:{})}));setDirty(true);setNotice('');}
 function choose(id:string){if(dirty&&!window.confirm('Há alterações não salvas. Descartar para trocar de projeto?'))return;const r=data?.projects.find(x=>x.id===id)||null;setRecord(r);setProject(r?.project||initial());setSceneRevision(x=>x+1);setDirty(false);setNotice('');setError('');}
 async function save(){if(data?.previewOnly)return;setBusy(true);setError('');try{const result=await api<Record>('/spatial-studio'+(record?'/'+record.id:''),record?'PATCH':'POST',{...(record?{version:record.version}:{}),project});setRecord(result);setProject(result.project);setDirty(false);setData(d=>d?{...d,projects:[result,...d.projects.filter(x=>x.id!==result.id)]}:d);setNotice('Projeto salvo no servidor.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function plan(){if(!record||dirty)return;setBusy(true);setError('');try{const result=await api<{plan:SpatialPlan;sourceVersion:number}>('/spatial-studio/'+record.id+'/plan','POST',{version:record.version});setProject(p=>({...p,plan:result.plan}));setDirty(true);setNotice('Plano recebido. Revise e salve para manter no projeto. Nenhum modelo foi gerado.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function composeScene(){if(!record||dirty)return;setBusy(true);setError('');try{const result=await api<{scene:SpatialScene}>('/spatial-studio/'+record.id+'/scene','POST',{version:record.version});update('scene',result.scene);setSceneRevision(x=>x+1);setNotice('Composição montada com IA. Explore e revise o cenário; salve para manter esta versão no projeto.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function exportPDF(internal=false){if(!estimate)return;setBusy(true);setError('');try{const {downloadSpatialPDF}=await import('./spatial-pdf');await downloadSpatialPDF(project,internal,dirty?undefined:record?.version);setNotice('PDF preparado com os dados atuais. '+(dirty?'As alterações ainda não foram salvas no portal.':''));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function exportProject(){if(!estimate)return;const blob=new Blob([JSON.stringify({product:'EME Spatial',status:'planning',project,estimate,automation:'Hipótese não medida; validar em piloto.',exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='eme-spatial-projeto.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function numberField(label:string,key:keyof SpatialProject,min:number,max:number,step=1,percent=false){return <label key={key}>{label}<input type="number" min={min} max={max} step={step} value={Number(project[key])*(percent?100:1)} onChange={e=>update(key,Number(e.target.value)/(percent?100:1))}/></label>;}
 return <div className="spatial-studio" aria-busy={busy}>
  <section className="spatial-banner"><div><span className="ps-overline">EME SPATIAL / STUDIO</span><h2>Do projeto ao espaço vivido.</h2><p>Uma produção organizada, reaproveitável e assistida por IA.</p><span className="spatial-stage">Projetos · oficina de cenários · propostas</span></div><Box size={54} strokeWidth={1}/></section>
  {error&&<div role="alert" className="pt-error">{error} <button className="ps-text-button" onClick={()=>{setError('');setReload(x=>x+1);}}>Atualizar lista</button></div>}
  {!data&&!error&&<p role="status">Carregando o estúdio…</p>}
  {data&&<>{data.previewOnly&&<p className="spatial-notice" role="status">Prévia do estúdio: o salvamento no servidor está indisponível. Você pode explorar os níveis e simular o orçamento. Exporte suas alterações antes de sair; elas não serão salvas no portal.</p>}<div className="spatial-toolbar"><label>Projeto<select disabled={busy} value={record?.id||''} onChange={e=>choose(e.target.value)}><option value="">Novo projeto · base G400</option>{data.projects.map(r=><option key={r.id} value={r.id}>{r.project.name}</option>)}</select></label><div><button className="ps-button" disabled={busy||!estimate} onClick={()=>exportPDF()}><Download size={16}/>Baixar proposta PDF</button><button className="ps-button ps-button--primary" disabled={busy||!estimate||data.previewOnly} onClick={save}><Save size={16}/>{busy?'Aguarde…':'Salvar projeto'}</button></div></div>
   {notice&&<p className="spatial-notice" role="status">{notice}</p>}
   <nav className="spatial-tabs" aria-label="Etapas do estúdio">{[['project','01 · Projeto'],['estimate','02 · Orçamento e prazo'],['production','03 · Cenário'],['proposal','04 · Proposta']].map(([id,label])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}>{label}</button>)}</nav>
   <fieldset className="spatial-editor" disabled={busy}>
   {tab==='project'&&<><section className="ps-card"><div className="ps-section-head"><div><span className="ps-overline">DEFINA A ENTREGA</span><h2>Qual experiência vamos construir?</h2></div><Layers3 size={24}/></div><div className="ps-form"><label>Nome do projeto<input value={project.name} maxLength={120} onChange={e=>update('name',e.target.value)}/></label><label>Objetivo e orientações de produção<textarea rows={3} maxLength={5000} value={project.brief} onChange={e=>update('brief',e.target.value)}/></label><div className="spatial-levels">{spatialLevels.map(l=><button type="button" aria-pressed={project.level===l.id} className={project.level===l.id?'is-selected':''} key={l.id} onClick={()=>{setProject(p=>applySpatialScope(p,p.scope,l.id));setDirty(true);}}><strong>{l.label}</strong><span>{l.description}</span></button>)}</div><label>Escopo inicial<select value={project.scope} onChange={e=>{setProject(p=>applySpatialScope(p,e.target.value));setDirty(true);}}><option value="pilot">Piloto · uma tipologia e um ambiente social</option><option value="full">G400 completo · 8 tipologias, áreas comuns e garagens</option><option value="custom">Escopo personalizado · informar horas</option></select></label></div><p className="spatial-help">{spatialLevels.find(l=>l.id===project.level)?.license} Licenças e manutenção são definidas por projeto, fora da simulação de implantação.</p></section>
    <section className="ps-card"><span className="ps-overline">ACERVO DE REFERÊNCIA / G400</span><h2>Começar pelo que já existe.</h2><p>12 plantas, 14 perspectivas, 8 tipologias e 31 unidades no cadastro. O acervo orienta o piloto; sua geometria ainda precisa de validação.</p><div className="spatial-references">{refs.map(([title,file])=><a key={file} href={base+file} target="_blank" rel="noreferrer"><img src={base+file} alt={title} loading="lazy"/><span>{title}<ArrowUpRight size={15}/></span></a>)}</div><p className="spatial-help">Acervo fixo do G400 nesta versão. Importação de novos arquivos e extração visual automatizada serão integradas ao fluxo de produção.</p></section></>}
   {tab==='estimate'&&<><div className="spatial-metrics" aria-live="polite">{[{label:'Esforço com a hipótese de automação',value:estimate?Math.ceil(estimate.remainingHours)+' h':'—',note:'Horas de equipe, não dias corridos'},{label:'Prazo calculado',value:estimate?estimate.weeks+' semanas':'—',note:'Capacidade informada + revisão'},{label:'Preço de referência',value:estimate?money(estimate.price):'—',note:'Produção, reserva, tributos e margem'},{label:'Valor a cobrar',value:estimate?money(estimate.payable):'—',note:project.courtesy===1?'Isenção integral G400':'Condição comercial simulada'}].map(x=><article key={x.label}><small>{x.label}</small><strong>{x.value}</strong><span>{x.note}</span></article>)}</div>
    <section className="ps-card"><h2>Automação como hipótese mensurável.</h2><p>O prazo reduzido só vira compromisso depois do piloto. Mediremos tempo de produção, revisão e retrabalho. Os presets são cenários de planejamento, sem medição de produtividade.</p><div className="ps-form spatial-inputs">{numberField('Horas manuais estimadas','manualHours',1,20000)}{numberField('Parte do trabalho automatizável (%)','automatableShare',0,100,5,true)}{numberField('Redução nessa parte (%)','reductionTarget',0,90,5,true)}{numberField('Pessoas equivalentes','people',1,30)}{numberField('Horas produtivas / pessoa / semana','hoursPerWeek',1,40)}{numberField('Semanas de revisão e dependências','reviewWeeks',0,52)}</div><p className="spatial-help">Horas restantes = horas manuais × (1 − parte automatizável × redução). Prazo = horas restantes ÷ capacidade semanal + revisão. {estimate&&`Base sem automação: ${estimate.baselineWeeks} semanas; economia simulada: ${Math.round(estimate.savedHours)} horas.`}</p></section>
    <section className="ps-card"><h2>Produção do cliente e investimento no produto.</h2><div className="ps-form spatial-inputs">{numberField('Custo econômico / hora (R$)','hourCost',1,2000)}{numberField('Recursos do projeto (R$)','resources',0,10000000,100)}{numberField('Reserva de incerteza (%)','contingency',0,80,1,true)}{numberField('Tributos estimados (%)','tax',0,50,1,true)}{numberField('Margem sobre receita (%)','margin',0,80,1,true)}{numberField('Isenção comercial (%)','courtesy',0,100,5,true)}{numberField('Investimento na plataforma (R$) · opcional','platformInvestment',0,10000000,100)}</div><p>{estimate?`Custo econômico estimado da produção: ${money(estimate.cost)}.`:'Confira os valores. Tributos e margem devem somar menos de 90%.'}</p><p className="spatial-help">Preço = custo com reserva ÷ (1 − tributos − margem), arredondado em R$1.000. O investimento no EME Spatial fica separado e não é cobrado integralmente de cada cliente. Zero nesse campo significa que o investimento ainda não foi estimado. Operação mensal não está incluída.</p></section></>}
   {tab==='production'&&<><Suspense fallback={<p>Carregando oficina…</p>}><SceneBuilder title={project.name} key={(record?.id||'new')+'-'+sceneRevision} scene={project.scene} onBuild={scene=>{update('scene',scene);setNotice('Cenário montado. Explore a composição e salve o projeto para manter esta versão.');}} onAI={composeScene} aiEnabled={data.aiReady&&!!record&&!dirty} busy={busy}/></Suspense><section className="ps-card"><div className="ps-section-head"><div><span className="ps-overline">ASSISTENTE DE PRODUÇÃO</span><h2>Um plano executável pela equipe.</h2></div><Sparkles size={24}/></div><p>A IA organiza etapas, dependências e reaproveitamento a partir do objetivo salvo. Revise o plano antes de salvar no projeto.</p><button className="ps-button ps-button--primary" onClick={plan} disabled={!data.aiReady||!record||dirty||busy}><Sparkles size={16}/>{busy?'Preparando plano…':'Criar plano com IA'}</button><p className="spatial-help">{!data.aiReady?'Ative a conexão na Central de IA. ':''}{(!record||dirty)?'Salve o projeto antes de solicitar o plano. ':''}Ao solicitar, nome, nível, escopo e objetivo são enviados à OpenAI. O uso pode gerar custo. Plantas e imagens não são enviadas nesta etapa.</p>{project.plan&&<article className="spatial-plan"><h3>Plano para revisão</h3><p>{project.plan.summary}</p><ol>{project.plan.steps.map((s,i)=><li key={i}>{s}</li>)}</ol><h4>Pendências e dependências</h4><p>{project.plan.risks}</p></article>}</section>
    <section className="spatial-roadmap ps-card"><span className="ps-overline">EVOLUÇÃO DO MOTOR DE PRODUÇÃO</span><h2>Da referência ao ambiente navegável.</h2>{[['Organizar e precificar','Disponível','Projetos salvos, níveis, hipóteses de prazo e custo.'],['Planejar com IA','Conexão necessária','Plano revisável a partir do objetivo do projeto.'],['Extrair e estruturar plantas','A desenvolver','Importação, medidas, cômodos e validação de geometria.'],['Montar e refinar cenas','Piloto disponível','Composição por imagens e piloto 3D Tipo 5 com acabamentos, luz, caminhada e exportação GLB. Outras geometrias ainda dependem de modelagem.'],['Gerar, revisar e publicar','A desenvolver','Fila de tarefas, custo máximo, versões, comparação e aprovação.']].map(([title,status,description])=><div key={title}><span>{status}</span><div><h3>{title}</h3><p>{description}</p></div></div>)}<p className="spatial-help">O piloto reutiliza a geometria conceitual do Tipo 5. A IA configura recursos existentes; não reconstrói plantas nem produz o nível Signature automaticamente. Nenhum cenário é publicado sem revisão.</p></section></>}
   {tab==='proposal'&&<section className="ps-card"><span className="ps-overline">APRESENTAÇÃO COMERCIAL / EME SPATIAL</span><h2>Uma proposta à altura da entrega.</h2><p>PDF com capa fotográfica, escopo, entregáveis, investimento, condições e direção visual. A capa usa a primeira referência do cenário montado.</p><div className="ps-form"><label>Preparado para<input maxLength={180} value={proposal.recipient} placeholder="Cliente ou incorporadora" onChange={e=>update('proposal',{...proposal,recipient:e.target.value})}/></label><label>Entregáveis específicos<textarea rows={5} maxLength={2500} value={proposal.deliverables} placeholder="Se não preencher, usamos os entregáveis do nível selecionado." onChange={e=>update('proposal',{...proposal,deliverables:e.target.value})}/></label><label>Condições da proposta<textarea rows={4} maxLength={1800} value={proposal.conditions} onChange={e=>update('proposal',{...proposal,conditions:e.target.value})}/></label></div><div className="spatial-document-actions"><button className="ps-button ps-button--primary" disabled={busy||!estimate} onClick={()=>exportPDF()}><Download size={16}/>Baixar PDF para o cliente</button><button className="ps-button" disabled={busy||!estimate} onClick={()=>exportPDF(true)}><Download size={16}/>Relatório interno em PDF</button><button className="ps-button" disabled={busy||!estimate} onClick={exportProject}>Exportar dados editáveis (.json)</button></div><p className="spatial-help">A proposta do cliente não inclui custo/hora, tributos, margem ou investimento na plataforma. O relatório interno acrescenta essas premissas. O PDF distingue a entrega prevista do cenário já montado e não substitui a aprovação do escopo.</p></section>}
   </fieldset>
  </>}
 </div>;
}

