import {randomUUID} from 'node:crypto';
export const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
export const fields=(body,keys)=>{if(!body||typeof body!=='object'||Array.isArray(body)||Object.keys(body).some(k=>!keys.includes(k)))fail(400,'Campos não permitidos.');};
export const text=(v,min=0,max=1200)=>{if(typeof v!=='string'||v.trim().length<min||v.trim().length>max)fail(400,'Confira o tamanho dos campos preenchidos.');return v.trim();};
export const types=['Casa','Casa em condomínio','Apartamento','Compacto','Cabana','Sala comercial','Loja','Edifício corporativo','Galpão','Pavilhão','Centro de distribuição','Terreno urbano','Lote em condomínio','Terra agrícola'];
export const closed=['Entrada aprovada','Não selecionado'];
export const admin=u=>{if(u.role!=='admin')fail(403,'Ação reservada ao administrador.');};
export const checkVersion=(row,body)=>{if(!Number.isInteger(body.version))fail(400,'Versão obrigatória.');if(row.version!==body.version)fail(409,'O cadastro mudou. Reabra para conferir a versão atual.');};
const strings=['privateAddress','ownerName','ownerContact','title','city','neighborhood','description','features','reasons','costNotes'];
const numbers=['price','area','bedrooms','suites','parking','condominiumFee','propertyTax'];
export function draft(input){fields(input,[...strings,...numbers,'type','environment','condominium','operation']);const result={};
 for(const k of strings)result[k]=text(input[k]??'',0,k==='description'?5000:1200);
 if(!result.title||!result.city)fail(400,'Informe título e cidade.');
 for(const [k,values]of [['type',types],['environment',['urbano','litoral','serra','industrial','comercial','terrenos']],['condominium',['','vertical','horizontal']],['operation',['comprar','alugar']]]){if(!values.includes(input[k]))fail(400,'Tipo, ambiente ou finalidade inválidos.');result[k]=input[k];}
 for(const k of numbers){const v=input[k]??null;if(v!==null&&(typeof v!=='number'||!Number.isFinite(v)||v<0||v>1e12||(['bedrooms','suites','parking'].includes(k)&&(!Number.isInteger(v)||v>1000))))fail(400,'Valor numérico inválido.');result[k]=v;}
 return result;
}
const criteria=[['physical','Condição física',30],['use','Adequação ao uso',25],['context','Contexto do local',20],['market','Coerência de mercado',25]];
const checks=[['authorization','Autorização e vínculo do solicitante'],['description','Características, áreas e uso informado'],['market','Fontes e comparáveis de mercado'],['documents','Revisão documental pelo responsável']];
export function curation(data){const saved=data.curation||{};const cs=criteria.map(([key,label,weight])=>({key,label,weight,help:'Registre evidências, fonte, data e limitações verificadas.',score:null,note:'',...saved.criteria?.find(x=>x.key===key)}));const vs=checks.map(([key,label])=>({key,label,state:'Pendente',note:'',author:null,date:null,...saved.checks?.find(x=>x.key===key)}));const complete=cs.every(c=>c.score!==null&&c.note.length>=10);const score=complete?Math.round(cs.reduce((s,c)=>s+c.score*c.weight/5,0)):null;const blockers=[];
 if(!complete)blockers.push('Complete as quatro notas e suas evidências.');if(score!==null&&(score<80||cs.some(c=>c.score<3)))blockers.push('Abaixo da régua piloto: 80/100 e mínimo 3 por dimensão.');for(const c of vs)if(c.state!=='Conferido'||c.note.length<10)blockers.push(c.label+': conferência pendente.');if(saved.pending?.trim())blockers.push('Resolva as pendências antes da decisão.');
 return {policy:'EME-piloto-01',criteria:cs,checks:vs,pending:saved.pending||'',score,blockers,coverage:cs.filter(c=>c.score!==null&&c.note.length>=10).length,locked:closed.includes(data.stage)};
}
export function reviseCuration(data,body,user){fields(body,['version','criteria','checks','pending']);if(closed.includes(data.stage))fail(409,'Reabra a decisão antes de alterar a curadoria.');if(!Array.isArray(body.criteria)||body.criteria.length!==4||!Array.isArray(body.checks)||body.checks.length!==4)fail(400,'Preencha os quatro critérios e verificações.');const prev=curation(data);
 const cs=prev.criteria.map(c=>{const entries=body.criteria.filter(x=>x?.key===c.key);if(entries.length!==1)fail(400,'Critério inválido.');const v=entries[0];fields(v,['key','score','note']);if(v.score!==null&&(!Number.isInteger(v.score)||v.score<0||v.score>5))fail(400,'Nota inválida.');return {key:c.key,score:v.score,note:text(v.note,v.score===null?0:10,1800)};});
 const vs=prev.checks.map(c=>{const entries=body.checks.filter(x=>x?.key===c.key);if(entries.length!==1)fail(400,'Verificação inválida.');const v=entries[0];fields(v,['key','state','note']);if(!['Pendente','Em revisão','Conferido'].includes(v.state))fail(400,'Verificação inválida.');const note=text(v.note,v.state==='Conferido'?10:0,1800),changed=note!==c.note||v.state!==c.state;if(changed&&(c.state==='Conferido'||v.state==='Conferido'))admin(user);return {key:c.key,state:v.state,note,author:changed?user.name:c.author,date:changed?new Date().toISOString():c.date};});
 return {...data,curation:{criteria:cs,checks:vs,pending:text(body.pending,0,3000)},stage:'Em avaliação',published:null};
}
export function decision(data,body,user){fields(body,['version','action','reason','acknowledged']);const action=body.action;if(!['submit','approve','reject','adjust','reopen'].includes(action))fail(400,'Decisão inválida.');text(body.reason,10,3000);if(action!=='submit')admin(user);const curr=curation(data);
 if(action==='reopen'&&!closed.includes(data.stage))fail(409,'Não existe decisão encerrada.');if(action!=='reopen'&&closed.includes(data.stage))fail(409,'Reabra a decisão.');if(action==='submit'&&data.stage==='Aguardando decisão')fail(409,'Já aguardando decisão.');if(action==='approve'&&data.stage!=='Aguardando decisão')fail(409,'Encaminhe para decisão antes da aprovação.');if(['submit','approve'].includes(action)&&curr.blockers.length)fail(409,curr.blockers.join(' '));if(action==='approve'&&body.acknowledged!==true)fail(400,'Confirme a revisão humana.');
 const next={...data,stage:{submit:'Aguardando decisão',approve:'Entrada aprovada',reject:'Não selecionado',adjust:'Ajustes solicitados',reopen:'Em avaliação'}[action]};if(action!=='approve')next.published=null;if(action==='reopen')next.curation={...curr,checks:curr.checks.map(c=>({...c,state:'Em revisão',author:user.name,date:new Date().toISOString()}))};return next;
}
export function changed(data){return {...data,stage:'Em avaliação',published:null,curation:{...curation(data),checks:curation(data).checks.map(c=>({...c,state:'Em revisão',author:null,date:null}))}};}
export function listingBlockers(data){const d=data.draft,errors=[];if(!d)return ['Cadastre as informações do anúncio.'];if(!d.price||!d.area)errors.push('Informe preço e área maiores que zero.');if(!d.neighborhood)errors.push('Informe bairro ou região pública.');if(d.description.length<80)errors.push('Descrição mínima de 80 caracteres.');if(!d.reasons.trim())errors.push('Registre os diferenciais EME.');if(!data.photos?.length)errors.push('Adicione fotografias reais.');if(data.photos?.some(p=>p.caption.trim().length<3))errors.push('Descreva cada fotografia.');if(data.stage!=='Entrada aprovada')errors.push('Conclua a curadoria e a aprovação.');return errors;}
export function publicProperty(row){const d=row.data.draft,images=(row.data.photos||[]).map(p=>({url:'/api/photos/'+p.id,caption:p.caption}));return {id:row.id,title:d.title,environment:d.environment,condominium:d.condominium||undefined,location:d.neighborhood+' · '+d.city,type:d.type==='Casa em condomínio'?'Casa':d.type,operation:d.operation,price:d.price,area:d.area,bedrooms:d.bedrooms,suites:d.suites,parking:d.parking,description:d.description,tags:d.features.split('\n').map(v=>v.trim()).filter(Boolean),reasons:d.reasons.split('\n').map(v=>v.trim()).filter(Boolean),costNotes:d.costNotes,condominiumFee:d.condominiumFee,propertyTax:d.propertyTax,image:images[0].url,images,isIllustrative:false,hasInterior:false};}
export function listing(row){return {id:row.id,version:row.version,draft:row.data.draft,photos:(row.data.photos||[]).map((p,position)=>({id:p.id,url:'/api/photos/'+p.id,width:p.width,height:p.height,caption:p.caption,position})),stage:row.data.stage,published:!!row.data.published&&row.data.stage==='Entrada aprovada',publishedVersion:row.data.published?row.version:null,blockers:listingBlockers(row.data)};}
export function evaluation(row,members){const d=row.data;return {id:row.id,title:d.title,city:d.city,type:d.type,operation:d.operation,owner:d.owner||'',assignee_id:row.assignee_id,assignee:members.find(x=>x.id===row.assignee_id)?.name||'Equipe',stage:d.stage,version:row.version,created_at:row.created_at,updated_at:row.updated_at};}
export const newCase=(input)=>({id:randomUUID(),data:{...input,stage:'Recebido',photos:[],published:null}});
