import { profilesFor } from '../../shared/locations.mjs';
import {randomUUID} from 'node:crypto';
import {readCuration,curationSnapshot} from '../curation-policy.mjs';
import {photoPublicationIssues} from '../../shared/photo-policy.mjs';
export const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
export const fields=(body,keys)=>{if(!body||typeof body!=='object'||Array.isArray(body)||Object.keys(body).some(k=>!keys.includes(k)))fail(400,'Campos não permitidos.');};
export const text=(v,min=0,max=1200)=>{if(typeof v!=='string'||v.trim().length<min||v.trim().length>max)fail(400,'Confira o tamanho dos campos preenchidos.');return v.trim();};
export const types=['Casa','Casa em condomínio','Apartamento','Compacto','Cabana','Cobertura','Sala comercial','Loja','Edifício corporativo','Galpão','Pavilhão','Centro de distribuição','Terreno urbano','Lote em condomínio','Terra agrícola'];
export const closed=['Entrada aprovada','Não selecionado'];
export const admin=u=>{if(u.role!=='admin')fail(403,'Ação reservada ao administrador.');};
export const checkVersion=(row,body)=>{if(!Number.isInteger(body.version))fail(400,'Versão obrigatória.');if(row.version!==body.version)fail(409,'O cadastro mudou. Reabra para conferir a versão atual.');};
const strings=['postalCode','privateAddress','ownerName','ownerContact','title','city','neighborhood','description','features','reasons','costNotes','sourceName','sourceUrl','sourceReference','sourceNotes','requesterRole','occupancy','documentationStatus','authorizationStatus','locationProfile'];
const numbers=['price','area','bedrooms','suites','parking','condominiumFee','propertyTax','bathrooms','totalArea','yearBuilt'];
export function draft(input){fields(input,[...strings,...numbers,'type','environment','condominium','operation']);const result={};
 for(const k of strings)result[k]=text(input[k]??'',0,k==='description'?5000:1200);
 if(!result.title||!result.city)fail(400,'Informe título e cidade.');
 for(const [k,values]of [['type',types],['environment',['urbano','litoral','serra','industrial','comercial','terrenos']],['condominium',['','vertical','horizontal']],['operation',['comprar','alugar']]]){if(!values.includes(input[k]))fail(400,'Tipo, ambiente ou finalidade inválidos.');result[k]=input[k];}
 for(const k of numbers){const v=input[k]??null;if(v!==null&&(typeof v!=='number'||!Number.isFinite(v)||v<0||v>1e12||(['bedrooms','suites','parking','bathrooms','yearBuilt'].includes(k)&&(!Number.isInteger(v)||v>(k==='yearBuilt'?2200:1000)))))fail(400,'Valor numérico inválido.');result[k]=v;}
 if(!profilesFor(result.environment).some(p=>p.value===result.locationProfile))fail(400,'Localização incompatível com o ambiente.');
 return result;
}
export function curation(data){return readCuration({saved:data.curation,type:data.draft?.type||data.type,stage:data.stage});}
export function reviseCuration(data,body,user){fields(body,['version','criteria','checks','pending']);if(closed.includes(data.stage))fail(409,'Reabra a decisão antes de alterar a curadoria.');const prev=curation(data);if(!Array.isArray(body.criteria)||body.criteria.length!==prev.criteria.length||!Array.isArray(body.checks)||body.checks.length!==prev.checks.length)fail(400,'Preencha os critérios e verificações esperados para esta versão da política.');
 const cs=prev.criteria.map(c=>{const entries=body.criteria.filter(x=>x?.key===c.key);if(entries.length!==1)fail(400,'Critério inválido.');const v=entries[0];fields(v,['key','score','note']);if(v.score!==null&&(!Number.isInteger(v.score)||v.score<0||v.score>5))fail(400,'Nota inválida.');return {key:c.key,score:v.score,note:text(v.note,v.score===null?0:10,1800)};});
 const vs=prev.checks.map(c=>{const entries=body.checks.filter(x=>x?.key===c.key);if(entries.length!==1)fail(400,'Verificação inválida.');const v=entries[0];fields(v,['key','state','note']);if(!['Pendente','Em revisão','Conferido'].includes(v.state))fail(400,'Verificação inválida.');const note=text(v.note,v.state==='Conferido'?10:0,1800),changed=note!==c.note||v.state!==c.state;if(changed&&(c.state==='Conferido'||v.state==='Conferido'))admin(user);return {key:c.key,state:v.state,note,author:changed?user.name:c.author,date:changed?new Date().toISOString():c.date};});
 return {...data,curation:curationSnapshot({...prev,criteria:cs,checks:vs,pending:text(body.pending,0,3000)}),stage:'Em avaliação',published:null};
}
export function decision(data,body,user){fields(body,['version','action','reason','acknowledged']);const action=body.action;if(!['submit','approve','reject','adjust','reopen'].includes(action))fail(400,'Decisão inválida.');text(body.reason,10,3000);if(action!=='submit')admin(user);const curr=curation(data);
 if(action==='reopen'&&!closed.includes(data.stage))fail(409,'Não existe decisão encerrada.');if(action!=='reopen'&&closed.includes(data.stage))fail(409,'Reabra a decisão.');if(action==='submit'&&data.stage==='Aguardando decisão')fail(409,'Já aguardando decisão.');if(action==='approve'&&data.stage!=='Aguardando decisão')fail(409,'Encaminhe para decisão antes da aprovação.');if(['submit','approve'].includes(action)&&curr.blockers.length)fail(409,curr.blockers.join(' '));if(action==='approve'&&body.acknowledged!==true)fail(400,'Confirme a revisão humana.');
 const next={...data,curation:curationSnapshot(curr),stage:{submit:'Aguardando decisão',approve:'Entrada aprovada',reject:'Não selecionado',adjust:'Ajustes solicitados',reopen:'Em avaliação'}[action]};if(action!=='approve')next.published=null;if(action==='reopen')next.curation=curationSnapshot({...curr,checks:curr.checks.map(c=>({...c,state:'Em revisão',author:user.name,date:new Date().toISOString()}))});return next;
}
export function changed(data){return {...data,stage:'Em avaliação',published:null,curation:{...curation(data),checks:curation(data).checks.map(c=>({...c,state:'Em revisão',author:null,date:null}))}};}
export function listingBlockers(data){const d=data.draft,errors=[];if(!d)return ['Cadastre as informações do anúncio.'];if(!d.price||!d.area)errors.push('Informe preço e área maiores que zero.');if(!d.neighborhood)errors.push('Informe bairro ou região pública.');if(d.description.length<80)errors.push('Descrição mínima de 80 caracteres.');if(!d.reasons.trim())errors.push('Registre os diferenciais EME.');errors.push(...photoPublicationIssues(data.photos));if(data.stage!=='Entrada aprovada')errors.push('Conclua a curadoria e a aprovação.');return errors;}
export function publicProperty(row){const d=row.data.draft,images=(row.data.photos||[]).map(p=>({url:'/api/photos/'+p.id,caption:p.caption,room:p.room||'',width:p.width,height:p.height}));return {id:row.id,title:d.title,environment:d.environment,locationProfile:d.locationProfile||undefined,condominium:d.condominium||undefined,location:d.neighborhood+' · '+d.city,type:d.type==='Casa em condomínio'?'Casa':d.type,operation:d.operation,price:d.price,area:d.area,bedrooms:d.bedrooms,suites:d.suites,parking:d.parking,bathrooms:d.bathrooms,totalArea:d.totalArea,yearBuilt:d.yearBuilt,description:d.description,tags:d.features.split('\n').map(v=>v.trim()).filter(Boolean),reasons:d.reasons.split('\n').map(v=>v.trim()).filter(Boolean),costNotes:d.costNotes,condominiumFee:d.condominiumFee,propertyTax:d.propertyTax,image:images[0].url,images,isIllustrative:false,hasInterior:false};}
export function listing(row){return {id:row.id,version:row.version,draft:row.data.draft,photos:(row.data.photos||[]).map((p,position)=>({id:p.id,url:'/api/photos/'+p.id,width:p.width,height:p.height,caption:p.caption,room:p.room||'',position,enhancement:p.enhancement||''})),stage:row.data.stage,published:!!row.data.published&&row.data.stage==='Entrada aprovada',publishedVersion:row.data.published?row.version:null,blockers:listingBlockers(row.data)};}
export function evaluation(row,members){const d=row.data;return {id:row.id,title:d.title,city:d.city,type:d.type,operation:d.operation,owner:d.owner||'',assignee_id:row.assignee_id,assignee:members.find(x=>x.id===row.assignee_id)?.name||'Equipe',stage:d.stage,version:row.version,created_at:row.created_at,updated_at:row.updated_at};}
export const newCase=(input)=>({id:randomUUID(),data:{...input,stage:'Recebido',photos:[],published:null}});
