export interface Meta { id:string; createdAt:string; updatedAt:string; createdBy:string }
export interface Ticket extends Meta { propertyId:string; title:string; contactName:string; contactPhone:string; channel:'whatsapp'|'phone'|'email'|'site'|'in_person'|'other'; status:'new'|'in_progress'|'waiting'|'closed'; assigneeId:string; priority:'normal'|'high'; nextContactAt:string|null; notes:string; messages:Array<{id:string;direction:'received'|'sent'|'internal';body:string;occurredAt:string;createdAt:string;createdBy:string}> }
export interface Visit extends Meta { propertyId:string; brokerId:string; visitorName:string; visitorPhone:string; startAt:string; endAt:string; status:'requested'|'confirmed'|'completed'|'cancelled'; notes:string; cancelReason:string|null; key:{status:'none'|'requested'|'authorized'|'out'|'returned';authorizedAt:string|null;authorizedBy:string|null;returnDueAt:string|null;pickedUpAt:string|null;returnedAt:string|null;custodianName:string;identityReference:string;notes:string} }
export interface Charge { id:string;month:string;rentCents:number;feeCents:number;ownerDueCents:number;status:'open'|'received'|'repassed'|'cancelled';dueDate:string;receivedAt:string|null;repassedAt:string|null;notes:string;createdAt:string;createdBy:string;updatedAt:string }
export interface Maintenance extends Meta {title:string;description:string;status:'open'|'in_progress'|'resolved';estimatedCostCents:number|null;actualCostCents:number|null;notes:string;reportedAt:string;resolvedAt:string|null}
export interface Inspection extends Meta {kind:'entry'|'periodic'|'exit';scheduledAt:string;completedAt:string|null;result:'pending'|'adequate'|'action_required';notes:string}
export interface Lease extends Meta {propertyId:string;ownerName:string;ownerPhone:string;tenantName:string;tenantPhone:string;startDate:string;endDate:string;rentCents:number;managementBps:number;dueDay:number;status:'active'|'ended';notes:string;endReason:string|null;charges:Charge[];maintenance:Maintenance[];inspections:Inspection[]}
export interface Document extends Meta {propertyId:string;title:string;category:'authorization'|'ownership'|'contract'|'inspection'|'other';filename:string;mimeType:string;sizeBytes:number;sha256:string;version:number;previousId:string|null;expiresOn:string|null;status:'pending'|'approved'|'rejected';reviewNotes:string;reviewedAt:string|null;reviewedBy:string|null}
export interface Review extends Meta {brokerId:string;periodStart:string;periodEnd:string;scores:{communication:number|null;followup:number|null;reliability:number|null;presentation:number|null};evidence:string;actionPlan:string;status:'draft'|'complete'}
export interface OperationsState {version:1;tickets:Ticket[];visits:Visit[];leases:Lease[];documents:Document[];reviews:Review[]}
export interface OperationsContext {actorId:string;role:'admin'|'corretor';now:string;members:Array<{id:string;name:string;role:string;active?:boolean}>;properties:Array<{id:string;title:string;assigneeId:string|null}>;file?:{filename:string;mimeType:string;sizeBytes:number;sha256:string}}
export interface OperationsCommand {type:string;data:Record<string,unknown>}
export interface OperationsMetrics {brokers:Array<{id:string;tickets:number;openTickets:number;overdueFollowups:number;visits:number;completedVisits:number;cancelledVisits:number}>;totals:{openTickets:number;upcomingVisits:number;keysOut:number;overdueKeys:number;activeLeases:number;openMaintenance:number;pendingDocuments:number}}
export class OperationsError extends Error {status:number;code:string}
export function emptyOperations():OperationsState
export function applyOperationsCommand(state:OperationsState,command:OperationsCommand,context:OperationsContext):OperationsState
export function operationsScope(state:OperationsState,command:OperationsCommand,context:OperationsContext):{propertyId:string|null;adminOnly:boolean}
export function visibleOperations(state:OperationsState,context:OperationsContext):OperationsState
export function operationsMetrics(state:OperationsState,asOf:string):OperationsMetrics
