import { chromium, expect } from '@playwright/test';
import { spawn } from 'node:child_process';
import { mkdirSync, mkdtempSync } from 'node:fs';
import { writeFile } from 'node:fs/promises';
import { resolve, join } from 'node:path';
mkdirSync('tmp',{recursive:true});
const temp=mkdtempSync(resolve('tmp/portal-team-e2e-'));
const port=4196, origin='http://127.0.0.1:'+port;
const server=spawn(process.execPath,['scripts/serve.mjs'],{env:{...process.env,EME_PREVIEW_PORT:String(port),EME_DB_PATH:join(temp,'portal.sqlite')},windowsHide:true,stdio:['ignore','pipe','pipe']});
let browser;
const checks=[],errors=[];
try{
  await new Promise((yes,no)=>{const timeout=setTimeout(()=>no(new Error('Server did not start')),10000);server.stdout.once('data',()=>{clearTimeout(timeout);yes();});server.once('exit',code=>{clearTimeout(timeout);no(new Error('Preview exited: '+code));});});
  browser=await chromium.launch({channel:'msedge',headless:true});
  const owner=await browser.newContext({viewport:{width:1440,height:1024}});
  const page=await owner.newPage();
  page.on('pageerror',error=>errors.push(error.message));
  await mkdirSync('design/portal-team',{recursive:true});
  await page.goto(origin+'/portalselect');
  await expect(page.getByRole('heading',{name:'Seu acesso começa aqui.'})).toBeVisible();
  await page.screenshot({path:'design/portal-team/setup-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'design/portal-team/setup-mobile.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.setViewportSize({width:1440,height:1024});
  await page.getByLabel('Seu nome',{exact:true}).fill('Administrador de teste');
  await page.getByLabel('E-mail',{exact:true}).fill('owner@example.test');
  await page.getByLabel('Senha',{exact:true}).fill('OnlyForTesting-2026-A!');
  await page.getByLabel('Confirme sua senha',{exact:true}).fill('OnlyForTesting-2026-A!');
  await page.getByRole('button',{name:'Criar meu acesso'}).click();
  await expect(page.getByRole('heading',{name:'Seu olhar. Agora, com continuidade.'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Seu primeiro imóvel começa aqui.'})).toBeVisible();
  checks.push('Initial account and empty real workspace');
  await page.screenshot({path:'design/portal-team/overview-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Nova avaliação',exact:true}).click();
  await page.getByLabel('Nome do imóvel',{exact:true}).fill('Casa de verificação');
  await page.getByLabel('Cidade e região').fill('Caxias do Sul');
  await page.getByRole('button',{name:'Cadastrar avaliação'}).click();
  const detail=page.getByRole('dialog');
  await expect(detail).toContainText('Cadastro criado');
  await detail.getByRole('combobox',{name:/^Etapa/}).selectOption('Em avaliação');
  await detail.getByLabel('Observação').fill('Conferir a área e os próximos documentos.');
  await detail.getByRole('button',{name:'Salvar acompanhamento'}).click();
  await expect(detail.locator('.pt-history')).toContainText('Conferir a área');
  await page.screenshot({path:'design/portal-team/dossier-desktop.png'});
  await page.keyboard.press('Escape');
  await page.reload();
  await expect(page.getByRole('button',{name:/Casa de verificação/}).first()).toBeVisible();
  expect(await page.evaluate(()=>Object.keys(localStorage).filter(key=>key.includes('portal')))).toEqual([]);
  checks.push('Database-backed create, note, history, reload; no real data in localStorage');
  await page.getByRole('navigation',{name:'Navegação da equipe'}).getByRole('link',{name:'Equipe e acessos'}).click();
  await page.getByRole('button',{name:'Adicionar pessoa'}).click();
  const form=page.getByRole('dialog');
  await form.getByLabel('Nome',{exact:true}).fill('Corretor de teste');
  await form.getByLabel('E-mail',{exact:true}).fill('broker@example.test');
  await form.getByLabel('Senha inicial').fill('OnlyForTesting-2026-A!');
  await form.getByRole('button',{name:'Criar acesso'}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.locator('.pt-team-row').filter({hasText:'Corretor de teste'})).toBeVisible();
  checks.push('Administrator can create staff account');
  const broker=await browser.newContext({viewport:{width:390,height:844}});
  const second=await broker.newPage();
  second.on('pageerror',error=>errors.push(error.message));
  await second.goto(origin+'/portalselect');
  await second.getByLabel('E-mail',{exact:true}).fill('broker@example.test');
  await second.getByLabel('Senha',{exact:true}).fill('OnlyForTesting-2026-A!');
  await second.getByRole('button',{name:'Entrar no portal'}).click();
  await expect(second.getByRole('heading',{name:'Uma senha só sua.'})).toBeVisible();
  await second.getByLabel('Senha atual').fill('OnlyForTesting-2026-A!');
  await second.getByLabel('Nova senha',{exact:true}).fill('OnlyForTesting-2026-B!');
  await second.getByLabel('Confirme a nova senha').fill('OnlyForTesting-2026-B!');
  await second.getByRole('button',{name:'Atualizar senha'}).click();
  await expect(second.getByRole('heading',{name:'Seu primeiro imóvel começa aqui.'})).toBeVisible({timeout:20000});
  await expect(second.locator('.pt-live')).not.toContainText('Casa de verificação');
  checks.push('First-login password change and isolated broker portfolio');
  await second.screenshot({path:'design/portal-team/overview-mobile.png',fullPage:true});
  expect(await second.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByRole('navigation',{name:'Navegação da equipe'}).getByRole('link',{name:'Avaliações',exact:true}).click();
  await page.getByRole('button',{name:'Abrir avaliação Casa de verificação'}).click();
  await page.getByRole('dialog').getByLabel('Responsável').selectOption({label:'Corretor de teste'});
  await page.getByRole('dialog').getByLabel('Observação').fill('Carteira atribuída para acompanhamento.');
  await page.getByRole('dialog').getByRole('button',{name:'Salvar acompanhamento'}).click();
  await expect(page.getByRole('dialog').locator('.pt-history')).toContainText('Carteira atribuída');
  await page.keyboard.press('Escape');
  await second.reload();
  await expect(second.getByRole('button',{name:/Casa de verificação/}).first()).toBeVisible();
  checks.push('Assignment grants access to the intended broker');
  await page.getByRole('navigation',{name:'Navegação da equipe'}).getByRole('link',{name:'Equipe e acessos'}).click();
  await page.locator('.pt-team-row').filter({hasText:'Corretor de teste'}).getByRole('button',{name:'Suspender'}).click();
  await page.getByRole('dialog').getByRole('button',{name:'Confirmar alteração'}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await second.reload();
  await expect(second.getByRole('heading',{name:'Bem-vindo de volta.'})).toBeVisible();
  checks.push('Suspension ends broker sessions');
  await page.getByRole('button',{name:'Sair da conta'}).click();
  await expect(page.getByRole('heading',{name:'Bem-vindo de volta.'})).toBeVisible();
  const anonymous=await owner.request.get(origin+'/api/evaluations');
  expect(anonymous.status()).toBe(401);
  expect((await owner.request.get(origin+'/.eme-private/portal.sqlite')).status()).toBe(404);
  checks.push('Logout and private database not publicly served');
  await expect(page.getByRole('link',{name:/demonstração/i})).toHaveCount(0);
  await page.goto(origin+'/portalselect/demo/locacoes');
  await expect(page).toHaveURL(/\/portalselect\/locacoes$/);
  await expect(page.getByRole('heading',{name:'Bem-vindo de volta.'})).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading',{name:'Bem-vindo de volta.'})).toBeVisible();
  checks.push('Legacy links enter the unified portal and still require authentication');
  expect(errors).toEqual([]);
  await writeFile('design/portal-team/verification.json',JSON.stringify({checks,errors},null,2));
  console.log(JSON.stringify({checks,errors}));
}finally{await browser?.close();server.kill();}
