import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,Plus} from 'lucide-react';
import {whatsappUrl} from './data';
import {Dialog} from './ui';
import './people.css';
export interface PublicPerson {id:string;name:string;role:string;bio:string;photoUrl:string;registration:string}
function PersonProfile({person,onClose}:{person:PublicPerson;onClose:()=>void}){
 return <Dialog title={'Perfil de '+person.name} onClose={onClose} wide className="eme-profile-dialog"><div className="eme-profile"><div className="eme-profile-visual"><span className="eme-profile-label">EME SELECT / PESSOAS</span><div className="eme-profile-portrait"><img src={person.photoUrl} alt={person.name} width="800" height="1000"/></div><span className="eme-profile-signature">Um olhar. Uma presença.</span></div><div className="eme-profile-story"><span className="eme-profile-overline">Quem faz a EME</span><h2>{person.name}</h2><p className="eme-profile-role">{person.role}</p>{person.bio&&<div className="eme-profile-bio">{person.bio.split(/\n+/).filter(Boolean).map((paragraph,i)=><p key={i}>{paragraph}</p>)}</div>}{person.registration&&<p className="eme-profile-registration">{person.registration}</p>}<a className="eme-profile-contact" href={whatsappUrl('Olá! Conheci o perfil de '+person.name+' no site e gostaria de conversar com a EME.')} target="_blank" rel="noopener noreferrer">Iniciar uma conversa <ArrowUpRight size={18}/></a><small>Atendimento pelo canal da EME Select.</small></div></div></Dialog>;
}
export default function PeopleSection(){
 const [people,setPeople]=useState<PublicPerson[]>([]),[activeId,setActiveId]=useState(''),[profile,setProfile]=useState<PublicPerson|null>(null);
 useEffect(()=>{const controller=new AbortController();fetch('/api/public/people',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(r=>setPeople(r.people||[])).catch(()=>{});return()=>controller.abort();},[]);
 const person=people.find(p=>p.id===activeId)||people[0],index=person?people.indexOf(person):0;
 function move(delta:number){setActiveId(people[(index+delta+people.length)%people.length].id);}
 return <section className="eme-people" id="quem-faz-a-eme" aria-labelledby="eme-people-title"><div className="eme-people-inner"><div className="eme-people-intro"><div><span className="eyebrow">Pessoas por trás de cada escolha</span><h2 id="eme-people-title">Quem faz a EME.</h2></div><p>Um lugar começa a fazer sentido quando alguém entende o que importa para você.</p></div>{person?<><div className="eme-people-stage"><img className="eme-people-landscape" src="/assets/scene-serra-bairro.webp" alt="" loading="lazy" aria-hidden="true"/><div className="eme-people-orbits" aria-hidden="true"/><div className="eme-people-stage-top"><span>ENCONTROS / EME SELECT</span><span>{String(index+1).padStart(2,'0')} <i>/</i> {String(people.length).padStart(2,'0')}</span></div><article key={person.id} className="eme-person"><div className="eme-person-content"><p className="eme-person-role">{person.role}</p><h3><button type="button" onClick={()=>setProfile(person)} aria-haspopup="dialog">{person.name}</button></h3>{person.bio&&<p className="eme-person-bio">{person.bio}</p>}<button type="button" className="eme-person-discover" onClick={()=>setProfile(person)} aria-haspopup="dialog">Conheça o perfil <span><ArrowUpRight size={18}/></span></button></div><div className="eme-person-frame"><span className="eme-person-frame-line" aria-hidden="true"/><button className="eme-person-photo" type="button" onClick={()=>setProfile(person)} aria-label={'Abrir perfil de '+person.name} aria-haspopup="dialog"><img src={person.photoUrl} alt={person.name} loading="lazy" width="800" height="1000"/><span className="eme-person-photo-open" aria-hidden="true"><Plus size={21}/></span></button><span className="eme-person-frame-caption">PRESENÇA QUE APROXIMA</span></div></article><div className="eme-people-stage-bottom"><span>Paisagem ilustrativa · Serra</span>{people.length>1&&<div className="eme-people-arrows"><button type="button" aria-label="Pessoa anterior" onClick={()=>move(-1)}><ArrowLeft size={17}/></button><button type="button" aria-label="Próxima pessoa" onClick={()=>move(1)}><ArrowRight size={17}/></button></div>}</div></div>{people.length>1&&<nav className="eme-people-roster" aria-label="Conheça as pessoas da EME">{people.map((entry,i)=><button type="button" key={entry.id} aria-pressed={entry.id===person.id} onClick={()=>setActiveId(entry.id)}><span className="eme-people-roster-number">{String(i+1).padStart(2,'0')}</span><span><strong>{entry.name}</strong><small>{entry.role}</small></span><ArrowUpRight size={15}/></button>)}</nav>}</>:<a className="text-link" href={whatsappUrl('Olá! Gostaria de conversar com a EME Select.')} target="_blank" rel="noopener noreferrer">Converse com a EME <ArrowUpRight size={17}/></a>}</div>{profile&&<PersonProfile person={profile} onClose={()=>setProfile(null)}/>}</section>;
}
