import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Maximize2,Pause,Play,X} from 'lucide-react';
import './property-gallery.css';
export default function PropertyGallery({images,title}:{images:{url:string;caption:string}[];title:string}){
 const [index,setIndex]=useState(0),[incoming,setIncoming]=useState<number|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[playing,setPlaying]=useState(true),[paused,setPaused]=useState(false),[reduced,setReduced]=useState(false);
 const token=useRef(0),target=useRef(0),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),dialog=useRef<HTMLDialogElement>(null),expand=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const m=matchMedia('(prefers-reduced-motion: reduce)');const change=()=>setReduced(m.matches);change();m.addEventListener('change',change);return()=>{m.removeEventListener('change',change);token.current++;clearTimeout(timer.current);};},[]);
 function go(next:number){if(images.length<2||loading||incoming!==null)return;const position=(next+images.length)%images.length;if(position===index&&incoming===null)return;target.current=position;const request=++token.current;clearTimeout(timer.current);setError('');setLoading(true);const image=new Image();image.src=images[position].url;image.decode().then(()=>{if(request!==token.current)return;setLoading(false);setIncoming(position);timer.current=setTimeout(()=>{if(request!==token.current)return;setIndex(position);setIncoming(null);},reduced?0:850);}).catch(()=>{if(request!==token.current)return;target.current=index;setLoading(false);setError('Esta foto não carregou. Tente novamente.');});}
 useEffect(()=>{if(!playing||paused||reduced||images.length<2)return;const tick=setInterval(()=>{if(document.visibilityState==='visible'&&!dialog.current?.open)go(target.current+1);},6500);return()=>clearInterval(tick);},[playing,paused,reduced,index,images,loading,incoming]);
 if(!images.length)return <div className="pg-empty">Adicione fotografias para visualizar a galeria.</div>;
 const controls=<div className="pg-controls"><button type="button" aria-label="Foto anterior" onClick={()=>go(target.current-1)} disabled={images.length<2||loading||incoming!==null}><ArrowLeft size={19}/></button><span aria-live="polite">{String(index+1).padStart(2,'0')} / {String(images.length).padStart(2,'0')}</span><button type="button" aria-label="Próxima foto" onClick={()=>go(target.current+1)} disabled={images.length<2||loading||incoming!==null}><ArrowRight size={19}/></button></div>;
 const stage=<div className="pg-stage"><img className="pg-photo" src={images[index].url} alt={images[index].caption||title} fetchPriority="high"/>{incoming!==null&&<img key={incoming} className="pg-photo pg-incoming" src={images[incoming].url} alt="" aria-hidden="true"/>}<div className="pg-caption"><span>{images[index].caption||title}</span>{controls}</div>{loading&&<span className="pg-loading" role="status">Preparando próxima foto…</span>}</div>;
 return <section className="property-gallery" aria-label={'Fotografias de '+title} onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} onFocusCapture={()=>setPaused(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget))setPaused(false);}} onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();go(target.current+1);}if(e.key==='ArrowLeft'){e.preventDefault();go(target.current-1);}}}>
 {stage}<div className="pg-toolbar"><span>Fotografias do imóvel</span><div>{images.length>1&&!reduced&&<button type="button" onClick={()=>setPlaying(!playing)} aria-label={playing?'Pausar apresentação':'Reproduzir apresentação'}>{playing?<Pause size={15}/>:<Play size={15}/>}<span>{playing?'Pausar':'Reproduzir'}</span></button>}<button ref={expand} type="button" onClick={()=>{dialog.current?.showModal();}}><Maximize2 size={15}/>Ampliar</button></div></div>
 {images.length>1&&<div className="pg-thumbnails" aria-label="Escolher fotografia">{images.map((photo,i)=><button type="button" key={photo.url} onClick={()=>go(i)} disabled={loading||incoming!==null} aria-label={'Ver foto '+(i+1)+': '+photo.caption} aria-current={index===i?'true':undefined}><img src={photo.url} alt="" loading="lazy"/></button>)}</div>}{error&&<p role="alert" className="pg-error">{error}</p>}
 <dialog ref={dialog} className="pg-dialog" aria-label={'Galeria ampliada de '+title} onClose={()=>expand.current?.focus()}><button className="pg-close" type="button" aria-label="Fechar galeria" onClick={()=>dialog.current?.close()}><X size={23}/></button>{stage}</dialog>
 </section>;
}
